// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.AuditLogEntry

/**
 * The audit management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class AuditApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/audit-logs`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param actorId the optional actor id filter, or null to omit it
     * @param action the optional action filter, or null to omit it
     * @param outcome the optional outcome filter, or null to omit it
     * @param resourceId the optional resource id filter, or null to omit it
     * @param from the optional from filter, or null to omit it
     * @param to the optional to filter, or null to omit it
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(actorId: String?, action: String?, outcome: String?, resourceId: String?, from: String?, to: String?, page: PageRequest?): Page<AuditLogEntry> {
        val path = "/api/v1/audit-logs"
        val query = ManagementSupport.pageQuery(mapOf("actor_id" to actorId, "action" to action, "outcome" to outcome, "resource_id" to resourceId, "from" to from, "to" to to), page)
        val node = transport.send(
            operation = "audit.list",
            method = "GET",
            pathTemplate = "/api/v1/audit-logs",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("audit.list", AuditLogEntry.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param actorId the optional actor id filter, or null to omit it
     * @param action the optional action filter, or null to omit it
     * @param outcome the optional outcome filter, or null to omit it
     * @param resourceId the optional resource id filter, or null to omit it
     * @param from the optional from filter, or null to omit it
     * @param to the optional to filter, or null to omit it
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(actorId: String?, action: String?, outcome: String?, resourceId: String?, from: String?, to: String?, start: PageRequest? = null): List<AuditLogEntry> =
        ManagementSupport.collectPages(start) { list(actorId, action, outcome, resourceId, from, to, it) }

    /**
     * Returns audit entries for unauthenticated/system requests (nil tenant_id). Requires
     * authentication — only logged-in users can query system audit logs.
     *
     * Issues `GET /api/v1/audit-logs/system`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `list_systemAll(...)` to walk every page.
     *
     * @param actorId the optional actor id filter, or null to omit it
     * @param action the optional action filter, or null to omit it
     * @param outcome the optional outcome filter, or null to omit it
     * @param resourceId the optional resource id filter, or null to omit it
     * @param from the optional from filter, or null to omit it
     * @param to the optional to filter, or null to omit it
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun listSystem(actorId: String?, action: String?, outcome: String?, resourceId: String?, from: String?, to: String?, page: PageRequest?): Page<AuditLogEntry> {
        val path = "/api/v1/audit-logs/system"
        val query = ManagementSupport.pageQuery(mapOf("actor_id" to actorId, "action" to action, "outcome" to outcome, "resource_id" to resourceId, "from" to from, "to" to to), page)
        val node = transport.send(
            operation = "audit.list_system",
            method = "GET",
            pathTemplate = "/api/v1/audit-logs/system",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("audit.list_system", AuditLogEntry.serializer(), node)
    }

    /**
     * Walks `listSystem` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param actorId the optional actor id filter, or null to omit it
     * @param action the optional action filter, or null to omit it
     * @param outcome the optional outcome filter, or null to omit it
     * @param resourceId the optional resource id filter, or null to omit it
     * @param from the optional from filter, or null to omit it
     * @param to the optional to filter, or null to omit it
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listSystemAll(actorId: String?, action: String?, outcome: String?, resourceId: String?, from: String?, to: String?, start: PageRequest? = null): List<AuditLogEntry> =
        ManagementSupport.collectPages(start) { listSystem(actorId, action, outcome, resourceId, from, to, it) }
}
