// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CaCertificate
import io.axiam.sdk.management.models.CreateCaCertificateRequest
import io.axiam.sdk.management.models.CreateIntermediateCaRequest
import io.axiam.sdk.management.models.GeneratedCaCertificate
import io.axiam.sdk.management.models.ImportCaCertificateRequest
import io.axiam.sdk.management.models.MigrateCustodyResponse
import io.axiam.sdk.management.models.MtlsTrustAnchorResponse
import io.axiam.sdk.management.models.SetMtlsTrustAnchor
import io.axiam.sdk.management.models.SignIntermediateCsrRequest
import java.util.UUID

/**
 * The ca_certificates management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class CaCertificatesApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Returns a handle addressing [orgId] instead of the client's organization.
     *
     * A NEW handle: this one is unchanged, so a scoped call cannot leak into unrelated code
     * holding the same reference (§27.4 rule 3).
     *
     * @param orgId the organization to address
     * @return a CaCertificatesApi scoped to [orgId]
     */
    fun inOrg(orgId: UUID): CaCertificatesApi =
        CaCertificatesApi(transport, scope.copy(orgId = orgId))

    /**
     * Issues `GET /api/v1/organizations/{org_id}/ca-certificates`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<CaCertificate> {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.list")
        val path = "/api/v1/organizations/${orgId}/ca-certificates"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "ca_certificates.list",
            method = "GET",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("ca_certificates.list", CaCertificate.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<CaCertificate> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Generate a CA. What that means depends on the configured key custodian, and deliberately not
     * on the request: * Under `database` or `vault` custody, AXIAM generates a self-signed root
     * and returns its private key once, in `private_key_pem`. * Under `vault_pki` custody, Vault
     * generates a root and a signing intermediate beneath it, and the response has **no**
     * `private_key_pem` because the key never existed outside Vault. The root's certificate comes
     * back in `chain_pem`, which is the only copy anything outside Vault will see.
     *
     * Issues `POST /api/v1/organizations/{org_id}/ca-certificates`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun generate(body: CreateCaCertificateRequest): GeneratedCaCertificate {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.generate")
        val path = "/api/v1/organizations/${orgId}/ca-certificates"
        val payload = ManagementSupport.encodeBody("ca_certificates.generate", CreateCaCertificateRequest.serializer(), body)
        val node = transport.send(
            operation = "ca_certificates.generate",
            method = "POST",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ca_certificates.generate", GeneratedCaCertificate.serializer(), node)
    }

    /**
     * Register a CA an organization already has, instead of generating one. The case this exists
     * for: an organization whose root lives offline, in an HSM, or in an existing internal PKI,
     * and which wants AXIAM in the chain rather than at the top of it. Without it, the only CA
     * AXIAM could use was one it generated, which means every AXIAM-issued certificate chains to a
     * root nothing else in the estate trusts. With a private key, AXIAM takes custody of it and
     * can issue against the CA. Where it goes is the configured custodian's business: sealed into
     * the row, written to Vault's KV engine, or — under `vault_pki` — imported into Vault's PKI
     * engine as an issuer, after which AXIAM signs through Vault and holds nothing. That last one
     * is the BYOK counterpart to generating in Vault: the key does pass through AXIAM's memory on
     * the way in, because AXIAM is what received the request, but it is never stored here and
     * every later use of it is Vault's. Without a private key, the certificate is a trust anchor
     * and `/api/v1/certificates` says so rather than failing at the point of use. Gated on
     * `ca_certificates:generate`: importing a CA is the same act as generating one from every
     * relying party's point of view — it decides what this organization's certificates chain to.
     *
     * Issues `POST /api/v1/organizations/{org_id}/ca-certificates/import`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun importCa(body: ImportCaCertificateRequest): CaCertificate {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.import_ca")
        val path = "/api/v1/organizations/${orgId}/ca-certificates/import"
        val payload = ManagementSupport.encodeBody("ca_certificates.import_ca", ImportCaCertificateRequest.serializer(), body)
        val node = transport.send(
            operation = "ca_certificates.import_ca",
            method = "POST",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates/import",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ca_certificates.import_ca", CaCertificate.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/organizations/{org_id}/ca-certificates/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): CaCertificate {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.get")
        val path = "/api/v1/organizations/${orgId}/ca-certificates/${id}"
        val node = transport.send(
            operation = "ca_certificates.get",
            method = "GET",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates/{id}",
            path = path,
        )
        return ManagementSupport.decode("ca_certificates.get", CaCertificate.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun revoke(id: UUID) {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.revoke")
        val path = "/api/v1/organizations/${orgId}/ca-certificates/${id}/revoke"
        transport.send(
            operation = "ca_certificates.revoke",
            method = "POST",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates/{id}/revoke",
            path = path,
        )
    }

    /**
     * Move this CA's signing key to the custodian the deployment is configured for. Custody is
     * recorded per CA rather than read from configuration, so adopting Vault does not move the CAs
     * that already exist — their keys stay sealed in their rows until something moves them. This
     * is that something, and without it the only route out of database custody is to generate a
     * new CA and re-issue every leaf beneath it, which for a trust anchor means touching every
     * relying party. Takes effect immediately; no restart. The row is the authority on where a key
     * lives, and the signing path reads it per request.
     *
     * Issues `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun migrateCustody(id: UUID): MigrateCustodyResponse {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.migrate_custody")
        val path = "/api/v1/organizations/${orgId}/ca-certificates/${id}/migrate-custody"
        val node = transport.send(
            operation = "ca_certificates.migrate_custody",
            method = "POST",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody",
            path = path,
        )
        return ManagementSupport.decode("ca_certificates.migrate_custody", MigrateCustodyResponse.serializer(), node)
    }

    /**
     * Offer this CA — or stop offering it — as a trust anchor for mutual TLS. When enabled, the
     * next server start exports this CA's **public** certificate into the client-CA bundle and
     * turns on client-certificate verification in `optional` mode, unless the operator has
     * configured `AXIAM__SERVER__TLS__CLIENT_AUTH` / `CLIENT_CA_PATH` themselves, which is never
     * overridden. The signing key is not copied and stays with its custodian. `restart_required`
     * is always true, and is the point of the response: there is no supported way to add a root to
     * a rustls listener that is already serving.
     *
     * Issues `PUT /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor`.
     *
     * A REPLACEMENT, not a patch: every field of the body is written, so read the current value
     * first and `copy()` the parts you mean to keep (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun setMtlsTrustAnchor(id: UUID, body: SetMtlsTrustAnchor): MtlsTrustAnchorResponse {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.set_mtls_trust_anchor")
        val path = "/api/v1/organizations/${orgId}/ca-certificates/${id}/mtls-trust-anchor"
        val payload = ManagementSupport.encodeBody("ca_certificates.set_mtls_trust_anchor", SetMtlsTrustAnchor.serializer(), body)
        val node = transport.send(
            operation = "ca_certificates.set_mtls_trust_anchor",
            method = "PUT",
            pathTemplate = "/api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ca_certificates.set_mtls_trust_anchor", MtlsTrustAnchorResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `list_signing_casAll(...)` to walk every page.
     *
     * @param tenantId the tenant id to address
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun listSigningCas(tenantId: UUID, page: PageRequest?): Page<CaCertificate> {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.list_signing_cas")
        val path = "/api/v1/organizations/${orgId}/tenants/${tenantId}/signing-cas"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "ca_certificates.list_signing_cas",
            method = "GET",
            pathTemplate = "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("ca_certificates.list_signing_cas", CaCertificate.serializer(), node)
    }

    /**
     * Walks `listSigningCas` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param tenantId the tenant id to address
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listSigningCasAll(tenantId: UUID, start: PageRequest? = null): List<CaCertificate> =
        ManagementSupport.collectPages(start) { listSigningCas(tenantId, it) }

    /**
     * Create a tenant signing CA beneath one of the organization's CAs, with the key generated by
     * whoever the deployment's custodian is. The private key is returned exactly once — and not at
     * all under `vault_pki`, where it was born inside Vault and no API exports it.
     *
     * Issues `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param tenantId the tenant id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun generateSigningCa(tenantId: UUID, body: CreateIntermediateCaRequest): GeneratedCaCertificate {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.generate_signing_ca")
        val path = "/api/v1/organizations/${orgId}/tenants/${tenantId}/signing-cas"
        val payload = ManagementSupport.encodeBody("ca_certificates.generate_signing_ca", CreateIntermediateCaRequest.serializer(), body)
        val node = transport.send(
            operation = "ca_certificates.generate_signing_ca",
            method = "POST",
            pathTemplate = "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ca_certificates.generate_signing_ca", GeneratedCaCertificate.serializer(), node)
    }

    /**
     * Sign a certificate signing request the tenant produced elsewhere. The response has no
     * `private_key_pem` because the key never reached AXIAM: it is wherever the CSR was made, and
     * that is the point of this endpoint rather than a shortcoming of it.
     *
     * Issues `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param tenantId the tenant id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun signSigningCaCsr(tenantId: UUID, body: SignIntermediateCsrRequest): CaCertificate {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "ca_certificates.sign_signing_ca_csr")
        val path = "/api/v1/organizations/${orgId}/tenants/${tenantId}/signing-cas/sign-csr"
        val payload = ManagementSupport.encodeBody("ca_certificates.sign_signing_ca_csr", SignIntermediateCsrRequest.serializer(), body)
        val node = transport.send(
            operation = "ca_certificates.sign_signing_ca_csr",
            method = "POST",
            pathTemplate = "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ca_certificates.sign_signing_ca_csr", CaCertificate.serializer(), node)
    }
}
