// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.Certificate
import io.axiam.sdk.management.models.CreateCertificateRequest
import io.axiam.sdk.management.models.GeneratedCertificate
import java.util.UUID

/**
 * The certificates management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class CertificatesApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/certificates`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<Certificate> {
        val path = "/api/v1/certificates"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "certificates.list",
            method = "GET",
            pathTemplate = "/api/v1/certificates",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("certificates.list", Certificate.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<Certificate> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/certificates`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun generate(body: CreateCertificateRequest): GeneratedCertificate {
        val path = "/api/v1/certificates"
        val payload = ManagementSupport.encodeBody("certificates.generate", CreateCertificateRequest.serializer(), body)
        val node = transport.send(
            operation = "certificates.generate",
            method = "POST",
            pathTemplate = "/api/v1/certificates",
            path = path, body = payload,
        )
        return ManagementSupport.decode("certificates.generate", GeneratedCertificate.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/certificates/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): Certificate {
        val path = "/api/v1/certificates/${id}"
        val node = transport.send(
            operation = "certificates.get",
            method = "GET",
            pathTemplate = "/api/v1/certificates/{id}",
            path = path,
        )
        return ManagementSupport.decode("certificates.get", Certificate.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/certificates/{id}/revoke`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun revoke(id: UUID) {
        val path = "/api/v1/certificates/${id}/revoke"
        transport.send(
            operation = "certificates.revoke",
            method = "POST",
            pathTemplate = "/api/v1/certificates/{id}/revoke",
            path = path,
        )
    }
}
