// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateFederationConfigRequest
import io.axiam.sdk.management.models.FederationConfigResponse
import io.axiam.sdk.management.models.FederationLinkResponse
import io.axiam.sdk.management.models.OidcAuthorizeRequest
import io.axiam.sdk.management.models.OidcAuthorizeResponse
import io.axiam.sdk.management.models.OidcCallbackRequest
import io.axiam.sdk.management.models.OidcCallbackResponse
import io.axiam.sdk.management.models.UpdateFederationConfigRequest
import java.util.UUID

/**
 * The federation management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class FederationApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/federation-configs`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `list_configsAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun listConfigs(page: PageRequest?): Page<FederationConfigResponse> {
        val path = "/api/v1/federation-configs"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "federation.list_configs",
            method = "GET",
            pathTemplate = "/api/v1/federation-configs",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("federation.list_configs", FederationConfigResponse.serializer(), node)
    }

    /**
     * Walks `listConfigs` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listConfigsAll(start: PageRequest? = null): List<FederationConfigResponse> =
        ManagementSupport.collectPages(start) { listConfigs(it) }

    /**
     * Issues `POST /api/v1/federation-configs`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun createConfig(body: CreateFederationConfigRequest): FederationConfigResponse {
        val path = "/api/v1/federation-configs"
        val payload = ManagementSupport.encodeBody("federation.create_config", CreateFederationConfigRequest.serializer(), body)
        val node = transport.send(
            operation = "federation.create_config",
            method = "POST",
            pathTemplate = "/api/v1/federation-configs",
            path = path, body = payload,
        )
        return ManagementSupport.decode("federation.create_config", FederationConfigResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/federation-configs/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun getConfig(id: UUID): FederationConfigResponse {
        val path = "/api/v1/federation-configs/${id}"
        val node = transport.send(
            operation = "federation.get_config",
            method = "GET",
            pathTemplate = "/api/v1/federation-configs/{id}",
            path = path,
        )
        return ManagementSupport.decode("federation.get_config", FederationConfigResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/federation-configs/{id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun updateConfig(id: UUID, body: UpdateFederationConfigRequest): FederationConfigResponse {
        val path = "/api/v1/federation-configs/${id}"
        val payload = ManagementSupport.encodeBody("federation.update_config", UpdateFederationConfigRequest.serializer(), body)
        val node = transport.send(
            operation = "federation.update_config",
            method = "PUT",
            pathTemplate = "/api/v1/federation-configs/{id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("federation.update_config", FederationConfigResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/federation-configs/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun deleteConfig(id: UUID) {
        val path = "/api/v1/federation-configs/${id}"
        transport.send(
            operation = "federation.delete_config",
            method = "DELETE",
            pathTemplate = "/api/v1/federation-configs/{id}",
            path = path,
        )
    }

    /**
     * Issues `GET /api/v1/federation-links/user/{user_id}`.
     *
     * @param userId the user id to address
     * @return the server response
     */
    suspend fun listUserLinks(userId: UUID): List<FederationLinkResponse> {
        val path = "/api/v1/federation-links/user/${userId}"
        val node = transport.send(
            operation = "federation.list_user_links",
            method = "GET",
            pathTemplate = "/api/v1/federation-links/user/{user_id}",
            path = path,
        )
        return ManagementSupport.decodeList("federation.list_user_links", FederationLinkResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/federation-links/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun deleteLink(id: UUID) {
        val path = "/api/v1/federation-links/${id}"
        transport.send(
            operation = "federation.delete_link",
            method = "DELETE",
            pathTemplate = "/api/v1/federation-links/{id}",
            path = path,
        )
    }

    /**
     * Builds the authorization URL for the external OIDC provider. The caller is responsible for
     * generating and storing `state` and `nonce` values for CSRF and replay protection.
     * TODO(T19.9): This endpoint currently requires authentication, making it usable only for
     * account-linking (already-authenticated users). Add separate unauthenticated federation login
     * endpoints that complete the external flow and return access/refresh tokens for first-time
     * login.
     *
     * Issues `POST /api/v1/federation/oidc/authorize`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun oidcAuthorize(body: OidcAuthorizeRequest): OidcAuthorizeResponse {
        val path = "/api/v1/federation/oidc/authorize"
        val payload = ManagementSupport.encodeBody("federation.oidc_authorize", OidcAuthorizeRequest.serializer(), body)
        val node = transport.send(
            operation = "federation.oidc_authorize",
            method = "POST",
            pathTemplate = "/api/v1/federation/oidc/authorize",
            path = path, body = payload,
        )
        return ManagementSupport.decode("federation.oidc_authorize", OidcAuthorizeResponse.serializer(), node)
    }

    /**
     * Handles the callback from the external OIDC provider after user authentication. Exchanges
     * the authorization code for tokens, validates the ID token, and provisions or links the local
     * user.
     *
     * Issues `POST /api/v1/federation/oidc/callback`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun oidcCallback(body: OidcCallbackRequest): OidcCallbackResponse {
        val path = "/api/v1/federation/oidc/callback"
        val payload = ManagementSupport.encodeBody("federation.oidc_callback", OidcCallbackRequest.serializer(), body)
        val node = transport.send(
            operation = "federation.oidc_callback",
            method = "POST",
            pathTemplate = "/api/v1/federation/oidc/callback",
            path = path, body = payload,
        )
        return ManagementSupport.decode("federation.oidc_callback", OidcCallbackResponse.serializer(), node)
    }
}
