// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport

/**
 * The CONTRACT.md §27 management API: 146 operations across 24 namespaces.
 *
 * Obtained from `client.management()`. Each accessor returns a namespace handle, which is a view
 * over the same session — acquiring one performs no I/O (§27.2 rule 1).
 *
 * The namespaces are grouped behind this one accessor rather than added to `AxiamClient` directly:
 * §27.2's own argument for handles is that a flat surface of 146 functions buries the twenty a
 * given caller needs, and hanging 24 more functions off the client would do to `AxiamClient`
 * exactly what the handles exist to prevent.
 */
class ManagementApi internal constructor(
    private val transport: ManagementTransport,
) {

    /**
     * The organizations operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the organizations namespace handle
     */
    fun organizations(): OrganizationsApi = OrganizationsApi(transport)

    /**
     * The tenants operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the tenants namespace handle
     */
    fun tenants(): TenantsApi = TenantsApi(transport)

    /**
     * The users operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the users namespace handle
     */
    fun users(): UsersApi = UsersApi(transport)

    /**
     * The groups operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the groups namespace handle
     */
    fun groups(): GroupsApi = GroupsApi(transport)

    /**
     * The roles operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the roles namespace handle
     */
    fun roles(): RolesApi = RolesApi(transport)

    /**
     * The permissions operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the permissions namespace handle
     */
    fun permissions(): PermissionsApi = PermissionsApi(transport)

    /**
     * The resources operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the resources namespace handle
     */
    fun resources(): ResourcesApi = ResourcesApi(transport)

    /**
     * The scopes operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the scopes namespace handle
     */
    fun scopes(): ScopesApi = ScopesApi(transport)

    /**
     * The service_accounts operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the service_accounts namespace handle
     */
    fun serviceAccounts(): ServiceAccountsApi = ServiceAccountsApi(transport)

    /**
     * The certificates operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the certificates namespace handle
     */
    fun certificates(): CertificatesApi = CertificatesApi(transport)

    /**
     * The ca_certificates operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the ca_certificates namespace handle
     */
    fun caCertificates(): CaCertificatesApi = CaCertificatesApi(transport)

    /**
     * The pgp_keys operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the pgp_keys namespace handle
     */
    fun pgpKeys(): PgpKeysApi = PgpKeysApi(transport)

    /**
     * The webhooks operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the webhooks namespace handle
     */
    fun webhooks(): WebhooksApi = WebhooksApi(transport)

    /**
     * The oauth2_clients operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the oauth2_clients namespace handle
     */
    fun oauth2Clients(): Oauth2ClientsApi = Oauth2ClientsApi(transport)

    /**
     * The federation operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the federation namespace handle
     */
    fun federation(): FederationApi = FederationApi(transport)

    /**
     * The notification_rules operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the notification_rules namespace handle
     */
    fun notificationRules(): NotificationRulesApi = NotificationRulesApi(transport)

    /**
     * The email_config operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the email_config namespace handle
     */
    fun emailConfig(): EmailConfigApi = EmailConfigApi(transport)

    /**
     * The settings operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the settings namespace handle
     */
    fun settings(): SettingsApi = SettingsApi(transport)

    /**
     * The scim_tokens operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the scim_tokens namespace handle
     */
    fun scimTokens(): ScimTokensApi = ScimTokensApi(transport)

    /**
     * The reactors operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the reactors namespace handle
     */
    fun reactors(): ReactorsApi = ReactorsApi(transport)

    /**
     * The webauthn_policy operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the webauthn_policy namespace handle
     */
    fun webauthnPolicy(): WebauthnPolicyApi = WebauthnPolicyApi(transport)

    /**
     * The audit operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the audit namespace handle
     */
    fun audit(): AuditApi = AuditApi(transport)

    /**
     * The privacy operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the privacy namespace handle
     */
    fun privacy(): PrivacyApi = PrivacyApi(transport)

    /**
     * The platform operations.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the platform namespace handle
     */
    fun platform(): PlatformApi = PlatformApi(transport)

    /**
     * The §27.6 declarative layer: describe the tenant you want, then reconcile.
     *
     * Acquiring the handle performs no I/O (§27.2 rule 1).
     *
     * @return the manifest handle
     */
    fun manifest(): ManifestApi = ManifestApi(this)
}
