// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateNotificationRuleRequest
import io.axiam.sdk.management.models.NotificationRuleResponse
import io.axiam.sdk.management.models.UpdateNotificationRuleRequest
import java.util.UUID

/**
 * The notification_rules management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class NotificationRulesApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/notification-rules`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<NotificationRuleResponse> {
        val path = "/api/v1/notification-rules"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "notification_rules.list",
            method = "GET",
            pathTemplate = "/api/v1/notification-rules",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("notification_rules.list", NotificationRuleResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<NotificationRuleResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/notification-rules`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateNotificationRuleRequest): NotificationRuleResponse {
        val path = "/api/v1/notification-rules"
        val payload = ManagementSupport.encodeBody("notification_rules.create", CreateNotificationRuleRequest.serializer(), body)
        val node = transport.send(
            operation = "notification_rules.create",
            method = "POST",
            pathTemplate = "/api/v1/notification-rules",
            path = path, body = payload,
        )
        return ManagementSupport.decode("notification_rules.create", NotificationRuleResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/notification-rules/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): NotificationRuleResponse {
        val path = "/api/v1/notification-rules/${id}"
        val node = transport.send(
            operation = "notification_rules.get",
            method = "GET",
            pathTemplate = "/api/v1/notification-rules/{id}",
            path = path,
        )
        return ManagementSupport.decode("notification_rules.get", NotificationRuleResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/notification-rules/{id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(id: UUID, body: UpdateNotificationRuleRequest): NotificationRuleResponse {
        val path = "/api/v1/notification-rules/${id}"
        val payload = ManagementSupport.encodeBody("notification_rules.update", UpdateNotificationRuleRequest.serializer(), body)
        val node = transport.send(
            operation = "notification_rules.update",
            method = "PUT",
            pathTemplate = "/api/v1/notification-rules/{id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("notification_rules.update", NotificationRuleResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/notification-rules/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun delete(id: UUID) {
        val path = "/api/v1/notification-rules/${id}"
        transport.send(
            operation = "notification_rules.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/notification-rules/{id}",
            path = path,
        )
    }
}
