// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateOAuth2ClientRequest
import io.axiam.sdk.management.models.OAuth2ClientCreatedResponse
import io.axiam.sdk.management.models.OAuth2ClientResponse
import io.axiam.sdk.management.models.UpdateOAuth2ClientRequest
import java.util.UUID

/**
 * The oauth2_clients management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class Oauth2ClientsApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/oauth2-clients`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<OAuth2ClientResponse> {
        val path = "/api/v1/oauth2-clients"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "oauth2_clients.list",
            method = "GET",
            pathTemplate = "/api/v1/oauth2-clients",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("oauth2_clients.list", OAuth2ClientResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<OAuth2ClientResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/oauth2-clients`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateOAuth2ClientRequest): OAuth2ClientCreatedResponse {
        val path = "/api/v1/oauth2-clients"
        val payload = ManagementSupport.encodeBody("oauth2_clients.create", CreateOAuth2ClientRequest.serializer(), body)
        val node = transport.send(
            operation = "oauth2_clients.create",
            method = "POST",
            pathTemplate = "/api/v1/oauth2-clients",
            path = path, body = payload,
        )
        return ManagementSupport.decode("oauth2_clients.create", OAuth2ClientCreatedResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/oauth2-clients/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): OAuth2ClientResponse {
        val path = "/api/v1/oauth2-clients/${id}"
        val node = transport.send(
            operation = "oauth2_clients.get",
            method = "GET",
            pathTemplate = "/api/v1/oauth2-clients/{id}",
            path = path,
        )
        return ManagementSupport.decode("oauth2_clients.get", OAuth2ClientResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/oauth2-clients/{id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(id: UUID, body: UpdateOAuth2ClientRequest): OAuth2ClientResponse {
        val path = "/api/v1/oauth2-clients/${id}"
        val payload = ManagementSupport.encodeBody("oauth2_clients.update", UpdateOAuth2ClientRequest.serializer(), body)
        val node = transport.send(
            operation = "oauth2_clients.update",
            method = "PUT",
            pathTemplate = "/api/v1/oauth2-clients/{id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("oauth2_clients.update", OAuth2ClientResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/oauth2-clients/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun delete(id: UUID) {
        val path = "/api/v1/oauth2-clients/${id}"
        transport.send(
            operation = "oauth2_clients.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/oauth2-clients/{id}",
            path = path,
        )
    }
}
