// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreatePgpKeyRequest
import io.axiam.sdk.management.models.EncryptRequest
import io.axiam.sdk.management.models.EncryptedExport
import io.axiam.sdk.management.models.GeneratedPgpKey
import io.axiam.sdk.management.models.PgpKey
import io.axiam.sdk.management.models.SignAuditBatchRequest
import io.axiam.sdk.management.models.SignedAuditBatch
import java.util.UUID

/**
 * The pgp_keys management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class PgpKeysApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/pgp-keys`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<PgpKey> {
        val path = "/api/v1/pgp-keys"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "pgp_keys.list",
            method = "GET",
            pathTemplate = "/api/v1/pgp-keys",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("pgp_keys.list", PgpKey.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<PgpKey> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/pgp-keys`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun generate(body: CreatePgpKeyRequest): GeneratedPgpKey {
        val path = "/api/v1/pgp-keys"
        val payload = ManagementSupport.encodeBody("pgp_keys.generate", CreatePgpKeyRequest.serializer(), body)
        val node = transport.send(
            operation = "pgp_keys.generate",
            method = "POST",
            pathTemplate = "/api/v1/pgp-keys",
            path = path, body = payload,
        )
        return ManagementSupport.decode("pgp_keys.generate", GeneratedPgpKey.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/pgp-keys/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): PgpKey {
        val path = "/api/v1/pgp-keys/${id}"
        val node = transport.send(
            operation = "pgp_keys.get",
            method = "GET",
            pathTemplate = "/api/v1/pgp-keys/{id}",
            path = path,
        )
        return ManagementSupport.decode("pgp_keys.get", PgpKey.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/pgp-keys/{id}/revoke`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun revoke(id: UUID) {
        val path = "/api/v1/pgp-keys/${id}/revoke"
        transport.send(
            operation = "pgp_keys.revoke",
            method = "POST",
            pathTemplate = "/api/v1/pgp-keys/{id}/revoke",
            path = path,
        )
    }

    /**
     * Issues `POST /api/v1/pgp-keys/{id}/encrypt`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun encrypt(id: UUID, body: EncryptRequest): EncryptedExport {
        val path = "/api/v1/pgp-keys/${id}/encrypt"
        val payload = ManagementSupport.encodeBody("pgp_keys.encrypt", EncryptRequest.serializer(), body)
        val node = transport.send(
            operation = "pgp_keys.encrypt",
            method = "POST",
            pathTemplate = "/api/v1/pgp-keys/{id}/encrypt",
            path = path, body = payload,
        )
        return ManagementSupport.decode("pgp_keys.encrypt", EncryptedExport.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/pgp-keys/sign-audit-batch`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun signAuditBatch(body: SignAuditBatchRequest): SignedAuditBatch {
        val path = "/api/v1/pgp-keys/sign-audit-batch"
        val payload = ManagementSupport.encodeBody("pgp_keys.sign_audit_batch", SignAuditBatchRequest.serializer(), body)
        val node = transport.send(
            operation = "pgp_keys.sign_audit_batch",
            method = "POST",
            pathTemplate = "/api/v1/pgp-keys/sign-audit-batch",
            path = path, body = payload,
        )
        return ManagementSupport.decode("pgp_keys.sign_audit_batch", SignedAuditBatch.serializer(), node)
    }
}
