// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.HealthResponse
import io.axiam.sdk.management.models.MdsRefreshOutcome
import io.axiam.sdk.management.models.MdsStatusResponse
import io.axiam.sdk.management.models.ReadyResponse

/**
 * The platform management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class PlatformApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /health`.
     *
     * @return the server response
     */
    suspend fun health(): HealthResponse {
        val path = "/health"
        val node = transport.send(
            operation = "platform.health",
            method = "GET",
            pathTemplate = "/health",
            path = path,
        )
        return ManagementSupport.decode("platform.health", HealthResponse.serializer(), node)
    }

    /**
     * Issues `GET /ready`.
     *
     * @return the server response
     */
    suspend fun ready(): ReadyResponse {
        val path = "/ready"
        val node = transport.send(
            operation = "platform.ready",
            method = "GET",
            pathTemplate = "/ready",
            path = path,
        )
        return ManagementSupport.decode("platform.ready", ReadyResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/mds/status`.
     *
     * @return the server response
     */
    suspend fun mdsStatus(): MdsStatusResponse {
        val path = "/api/v1/mds/status"
        val node = transport.send(
            operation = "platform.mds_status",
            method = "GET",
            pathTemplate = "/api/v1/mds/status",
            path = path,
        )
        return ManagementSupport.decode("platform.mds_status", MdsStatusResponse.serializer(), node)
    }

    /**
     * Fetches (or, when `AXIAM__PKI__MDS_BLOB_PATH` is set, loads locally), verifies, and ingests
     * the FIDO MDS3 BLOB. Refuses to run when MDS ingestion is disabled
     * (`AXIAM__PKI__MDS_ENABLED=false`, the default) — per `PkiConfig`'s documented contract, the
     * master switch being off means this endpoint makes no outbound call at all, not just that the
     * background job doesn't run.
     *
     * Issues `POST /api/v1/mds/refresh`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @return the server response
     */
    suspend fun mdsRefresh(): MdsRefreshOutcome {
        val path = "/api/v1/mds/refresh"
        val node = transport.send(
            operation = "platform.mds_refresh",
            method = "POST",
            pathTemplate = "/api/v1/mds/refresh",
            path = path,
        )
        return ManagementSupport.decode("platform.mds_refresh", MdsRefreshOutcome.serializer(), node)
    }
}
