// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateReactorRequest
import io.axiam.sdk.management.models.ReactorEventDescriptor
import io.axiam.sdk.management.models.ReactorResponse
import io.axiam.sdk.management.models.UpdateReactorRequest
import java.util.UUID

/**
 * The reactors management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class ReactorsApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/reactors`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<ReactorResponse> {
        val path = "/api/v1/reactors"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "reactors.list",
            method = "GET",
            pathTemplate = "/api/v1/reactors",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("reactors.list", ReactorResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<ReactorResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/reactors`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateReactorRequest): ReactorResponse {
        val path = "/api/v1/reactors"
        val payload = ManagementSupport.encodeBody("reactors.create", CreateReactorRequest.serializer(), body)
        val node = transport.send(
            operation = "reactors.create",
            method = "POST",
            pathTemplate = "/api/v1/reactors",
            path = path, body = payload,
        )
        return ManagementSupport.decode("reactors.create", ReactorResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/reactors/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): ReactorResponse {
        val path = "/api/v1/reactors/${id}"
        val node = transport.send(
            operation = "reactors.get",
            method = "GET",
            pathTemplate = "/api/v1/reactors/{id}",
            path = path,
        )
        return ManagementSupport.decode("reactors.get", ReactorResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/reactors/{id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(id: UUID, body: UpdateReactorRequest): ReactorResponse {
        val path = "/api/v1/reactors/${id}"
        val payload = ManagementSupport.encodeBody("reactors.update", UpdateReactorRequest.serializer(), body)
        val node = transport.send(
            operation = "reactors.update",
            method = "PUT",
            pathTemplate = "/api/v1/reactors/{id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("reactors.update", ReactorResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/reactors/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun delete(id: UUID) {
        val path = "/api/v1/reactors/${id}"
        transport.send(
            operation = "reactors.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/reactors/{id}",
            path = path,
        )
    }

    /**
     * Served rather than documented so an admin UI, an SDK generator and an operator all read the
     * same list the dispatcher enforces. A hand-maintained copy in the docs is a copy that goes
     * stale on the next hook added.
     *
     * Issues `GET /api/v1/reactors/events`.
     *
     * @return the server response
     */
    suspend fun listEvents(): List<ReactorEventDescriptor> {
        val path = "/api/v1/reactors/events"
        val node = transport.send(
            operation = "reactors.list_events",
            method = "GET",
            pathTemplate = "/api/v1/reactors/events",
            path = path,
        )
        return ManagementSupport.decodeList("reactors.list_events", ReactorEventDescriptor.serializer(), node)
    }
}
