// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateResourceRequest
import io.axiam.sdk.management.models.Resource
import io.axiam.sdk.management.models.UpdateResourceRequest
import java.util.UUID

/**
 * The resources management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class ResourcesApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/resources`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<Resource> {
        val path = "/api/v1/resources"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "resources.list",
            method = "GET",
            pathTemplate = "/api/v1/resources",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("resources.list", Resource.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<Resource> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/resources`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateResourceRequest): Resource {
        val path = "/api/v1/resources"
        val payload = ManagementSupport.encodeBody("resources.create", CreateResourceRequest.serializer(), body)
        val node = transport.send(
            operation = "resources.create",
            method = "POST",
            pathTemplate = "/api/v1/resources",
            path = path, body = payload,
        )
        return ManagementSupport.decode("resources.create", Resource.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/resources/{resource_id}`.
     *
     * @param resourceId the resource id to address
     * @return the server response
     */
    suspend fun get(resourceId: UUID): Resource {
        val path = "/api/v1/resources/${resourceId}"
        val node = transport.send(
            operation = "resources.get",
            method = "GET",
            pathTemplate = "/api/v1/resources/{resource_id}",
            path = path,
        )
        return ManagementSupport.decode("resources.get", Resource.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/resources/{resource_id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param resourceId the resource id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(resourceId: UUID, body: UpdateResourceRequest): Resource {
        val path = "/api/v1/resources/${resourceId}"
        val payload = ManagementSupport.encodeBody("resources.update", UpdateResourceRequest.serializer(), body)
        val node = transport.send(
            operation = "resources.update",
            method = "PUT",
            pathTemplate = "/api/v1/resources/{resource_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("resources.update", Resource.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/resources/{resource_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param resourceId the resource id to address
     */
    suspend fun delete(resourceId: UUID) {
        val path = "/api/v1/resources/${resourceId}"
        transport.send(
            operation = "resources.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/resources/{resource_id}",
            path = path,
        )
    }

    /**
     * Issues `GET /api/v1/resources/{resource_id}/children`.
     *
     * @param resourceId the resource id to address
     * @return the server response
     */
    suspend fun listChildren(resourceId: UUID): List<Resource> {
        val path = "/api/v1/resources/${resourceId}/children"
        val node = transport.send(
            operation = "resources.list_children",
            method = "GET",
            pathTemplate = "/api/v1/resources/{resource_id}/children",
            path = path,
        )
        return ManagementSupport.decodeList("resources.list_children", Resource.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/resources/{resource_id}/ancestors`.
     *
     * @param resourceId the resource id to address
     * @return the server response
     */
    suspend fun listAncestors(resourceId: UUID): List<Resource> {
        val path = "/api/v1/resources/${resourceId}/ancestors"
        val node = transport.send(
            operation = "resources.list_ancestors",
            method = "GET",
            pathTemplate = "/api/v1/resources/{resource_id}/ancestors",
            path = path,
        )
        return ManagementSupport.decodeList("resources.list_ancestors", Resource.serializer(), node)
    }
}
