// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.AssignRoleToGroupRequest
import io.axiam.sdk.management.models.AssignRoleToServiceAccountRequest
import io.axiam.sdk.management.models.AssignRoleToUserRequest
import io.axiam.sdk.management.models.CreateRoleRequest
import io.axiam.sdk.management.models.GrantPermissionRequest
import io.axiam.sdk.management.models.ResolvedPermissionGrant
import io.axiam.sdk.management.models.Role
import io.axiam.sdk.management.models.RoleGroupAssignment
import io.axiam.sdk.management.models.RoleServiceAccountAssignment
import io.axiam.sdk.management.models.RoleUserAssignment
import io.axiam.sdk.management.models.UpdateRole
import java.util.UUID

/**
 * The roles management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class RolesApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/roles`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<Role> {
        val path = "/api/v1/roles"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "roles.list",
            method = "GET",
            pathTemplate = "/api/v1/roles",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("roles.list", Role.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<Role> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/roles`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateRoleRequest): Role {
        val path = "/api/v1/roles"
        val payload = ManagementSupport.encodeBody("roles.create", CreateRoleRequest.serializer(), body)
        val node = transport.send(
            operation = "roles.create",
            method = "POST",
            pathTemplate = "/api/v1/roles",
            path = path, body = payload,
        )
        return ManagementSupport.decode("roles.create", Role.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/roles/{role_id}`.
     *
     * @param roleId the role id to address
     * @return the server response
     */
    suspend fun get(roleId: UUID): Role {
        val path = "/api/v1/roles/${roleId}"
        val node = transport.send(
            operation = "roles.get",
            method = "GET",
            pathTemplate = "/api/v1/roles/{role_id}",
            path = path,
        )
        return ManagementSupport.decode("roles.get", Role.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/roles/{role_id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(roleId: UUID, body: UpdateRole): Role {
        val path = "/api/v1/roles/${roleId}"
        val payload = ManagementSupport.encodeBody("roles.update", UpdateRole.serializer(), body)
        val node = transport.send(
            operation = "roles.update",
            method = "PUT",
            pathTemplate = "/api/v1/roles/{role_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("roles.update", Role.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/roles/{role_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     */
    suspend fun delete(roleId: UUID) {
        val path = "/api/v1/roles/${roleId}"
        transport.send(
            operation = "roles.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/roles/{role_id}",
            path = path,
        )
    }

    /**
     * Lists this role's user assignments (the inverse of `GET /users/{user_id}/roles`). Used by
     * the role detail page's members panel. Directly-assigned users only — a user who reaches this
     * role through a group is not a member of it and has no grant here to revoke. `resource_id`
     * says whether the grant is global or applies only under one resource; `has_role` is
     * `UNIQUE(in, out)`, so each user appears at most once.
     *
     * Issues `GET /api/v1/roles/{role_id}/users`.
     *
     * @param roleId the role id to address
     * @return the server response
     */
    suspend fun listUsers(roleId: UUID): List<RoleUserAssignment> {
        val path = "/api/v1/roles/${roleId}/users"
        val node = transport.send(
            operation = "roles.list_users",
            method = "GET",
            pathTemplate = "/api/v1/roles/{role_id}/users",
            path = path,
        )
        return ManagementSupport.decodeList("roles.list_users", RoleUserAssignment.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/roles/{role_id}/users`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param body the request body
     */
    suspend fun assignToUser(roleId: UUID, body: AssignRoleToUserRequest) {
        val path = "/api/v1/roles/${roleId}/users"
        val payload = ManagementSupport.encodeBody("roles.assign_to_user", AssignRoleToUserRequest.serializer(), body)
        transport.send(
            operation = "roles.assign_to_user",
            method = "POST",
            pathTemplate = "/api/v1/roles/{role_id}/users",
            path = path, body = payload,
        )
    }

    /**
     * Issues `DELETE /api/v1/roles/{role_id}/users/{user_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param userId the user id to address
     * @param resourceId the optional resource id filter, or null to omit it
     */
    suspend fun unassignFromUser(roleId: UUID, userId: UUID, resourceId: String?) {
        val path = "/api/v1/roles/${roleId}/users/${userId}"
        val query = mapOf("resource_id" to resourceId)
        transport.send(
            operation = "roles.unassign_from_user",
            method = "DELETE",
            pathTemplate = "/api/v1/roles/{role_id}/users/{user_id}",
            path = path, query = query,
        )
    }

    /**
     * Lists this role's group assignments (the inverse of `GET /groups/{group_id}/roles`), each
     * with the resource it is scoped to — see &#91;`list_users`&#93; for why that field is here.
     *
     * Issues `GET /api/v1/roles/{role_id}/groups`.
     *
     * @param roleId the role id to address
     * @return the server response
     */
    suspend fun listGroups(roleId: UUID): List<RoleGroupAssignment> {
        val path = "/api/v1/roles/${roleId}/groups"
        val node = transport.send(
            operation = "roles.list_groups",
            method = "GET",
            pathTemplate = "/api/v1/roles/{role_id}/groups",
            path = path,
        )
        return ManagementSupport.decodeList("roles.list_groups", RoleGroupAssignment.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/roles/{role_id}/groups`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param body the request body
     */
    suspend fun assignToGroup(roleId: UUID, body: AssignRoleToGroupRequest) {
        val path = "/api/v1/roles/${roleId}/groups"
        val payload = ManagementSupport.encodeBody("roles.assign_to_group", AssignRoleToGroupRequest.serializer(), body)
        transport.send(
            operation = "roles.assign_to_group",
            method = "POST",
            pathTemplate = "/api/v1/roles/{role_id}/groups",
            path = path, body = payload,
        )
    }

    /**
     * Issues `DELETE /api/v1/roles/{role_id}/groups/{group_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param groupId the group id to address
     * @param resourceId the optional resource id filter, or null to omit it
     */
    suspend fun unassignFromGroup(roleId: UUID, groupId: UUID, resourceId: String?) {
        val path = "/api/v1/roles/${roleId}/groups/${groupId}"
        val query = mapOf("resource_id" to resourceId)
        transport.send(
            operation = "roles.unassign_from_group",
            method = "DELETE",
            pathTemplate = "/api/v1/roles/{role_id}/groups/{group_id}",
            path = path, query = query,
        )
    }

    /**
     * Issues `GET /api/v1/roles/{role_id}/permissions`.
     *
     * @param roleId the role id to address
     * @return the server response
     */
    suspend fun listPermissions(roleId: UUID): List<ResolvedPermissionGrant> {
        val path = "/api/v1/roles/${roleId}/permissions"
        val node = transport.send(
            operation = "roles.list_permissions",
            method = "GET",
            pathTemplate = "/api/v1/roles/{role_id}/permissions",
            path = path,
        )
        return ManagementSupport.decodeList("roles.list_permissions", ResolvedPermissionGrant.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/roles/{role_id}/permissions`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param body the request body
     */
    suspend fun grantPermission(roleId: UUID, body: GrantPermissionRequest) {
        val path = "/api/v1/roles/${roleId}/permissions"
        val payload = ManagementSupport.encodeBody("roles.grant_permission", GrantPermissionRequest.serializer(), body)
        transport.send(
            operation = "roles.grant_permission",
            method = "POST",
            pathTemplate = "/api/v1/roles/{role_id}/permissions",
            path = path, body = payload,
        )
    }

    /**
     * Issues `DELETE /api/v1/roles/{role_id}/permissions/{permission_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param permissionId the permission id to address
     */
    suspend fun revokePermission(roleId: UUID, permissionId: UUID) {
        val path = "/api/v1/roles/${roleId}/permissions/${permissionId}"
        transport.send(
            operation = "roles.revoke_permission",
            method = "DELETE",
            pathTemplate = "/api/v1/roles/{role_id}/permissions/{permission_id}",
            path = path,
        )
    }

    /**
     * Issues `GET /api/v1/roles/{role_id}/service-accounts`.
     *
     * @param roleId the role id to address
     * @return the server response
     */
    suspend fun listServiceAccounts(roleId: UUID): List<RoleServiceAccountAssignment> {
        val path = "/api/v1/roles/${roleId}/service-accounts"
        val node = transport.send(
            operation = "roles.list_service_accounts",
            method = "GET",
            pathTemplate = "/api/v1/roles/{role_id}/service-accounts",
            path = path,
        )
        return ManagementSupport.decodeList("roles.list_service_accounts", RoleServiceAccountAssignment.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/roles/{role_id}/service-accounts`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param body the request body
     */
    suspend fun assignToServiceAccount(roleId: UUID, body: AssignRoleToServiceAccountRequest) {
        val path = "/api/v1/roles/${roleId}/service-accounts"
        val payload = ManagementSupport.encodeBody("roles.assign_to_service_account", AssignRoleToServiceAccountRequest.serializer(), body)
        transport.send(
            operation = "roles.assign_to_service_account",
            method = "POST",
            pathTemplate = "/api/v1/roles/{role_id}/service-accounts",
            path = path, body = payload,
        )
    }

    /**
     * Issues `DELETE /api/v1/roles/{role_id}/service-accounts/{service_account_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param roleId the role id to address
     * @param serviceAccountId the service account id to address
     * @param resourceId the optional resource id filter, or null to omit it
     */
    suspend fun unassignFromServiceAccount(roleId: UUID, serviceAccountId: UUID, resourceId: String?) {
        val path = "/api/v1/roles/${roleId}/service-accounts/${serviceAccountId}"
        val query = mapOf("resource_id" to resourceId)
        transport.send(
            operation = "roles.unassign_from_service_account",
            method = "DELETE",
            pathTemplate = "/api/v1/roles/{role_id}/service-accounts/{service_account_id}",
            path = path, query = query,
        )
    }
}
