// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.IssueSamlIdpCredential
import io.axiam.sdk.management.models.ParseSamlSpMetadata
import io.axiam.sdk.management.models.SamlIdpCredential
import io.axiam.sdk.management.models.SamlIdpCredentialPromotion
import io.axiam.sdk.management.models.SamlIdpInfo
import io.axiam.sdk.management.models.SamlServiceProvider
import io.axiam.sdk.management.models.SamlServiceProviderInput
import io.axiam.sdk.management.models.SamlSpMetadataDraft
import java.util.UUID

/**
 * The saml management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class SamlApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Returns a handle addressing [tenantId] instead of the client's tenant.
     *
     * A NEW handle: this one is unchanged (§27.4 rule 3).
     *
     * @param tenantId the tenant to address
     * @return a SamlApi scoped to [tenantId]
     */
    fun forTenant(tenantId: UUID): SamlApi =
        SamlApi(transport, scope.copy(tenantId = tenantId))

    /**
     * The tenant's IdP as an SP will meet it, and whether it answers yet: readiness is visible
     * only here, never on the unauthenticated metadata route (T-368).
     *
     * Issues `GET /api/v1/tenants/{tenant_id}/saml/idp`.
     *
     * @return the server response
     */
    suspend fun getIdp(): SamlIdpInfo {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.get_idp")
        val path = "/api/v1/tenants/${tenantId}/saml/idp"
        val node = transport.send(
            operation = "saml.get_idp",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/idp",
            path = path,
        )
        return ManagementSupport.decode("saml.get_idp", SamlIdpInfo.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/saml/service-providers`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `list_service_providersAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun listServiceProviders(page: PageRequest?): Page<SamlServiceProvider> {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.list_service_providers")
        val path = "/api/v1/tenants/${tenantId}/saml/service-providers"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "saml.list_service_providers",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/service-providers",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("saml.list_service_providers", SamlServiceProvider.serializer(), node)
    }

    /**
     * Walks `listServiceProviders` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listServiceProvidersAll(start: PageRequest? = null): List<SamlServiceProvider> =
        ManagementSupport.collectPages(start) { listServiceProviders(it) }

    /**
     * Issues `POST /api/v1/tenants/{tenant_id}/saml/service-providers`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun createServiceProvider(body: SamlServiceProviderInput): SamlServiceProvider {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.create_service_provider")
        val path = "/api/v1/tenants/${tenantId}/saml/service-providers"
        val payload = ManagementSupport.encodeBody("saml.create_service_provider", SamlServiceProviderInput.serializer(), body)
        val node = transport.send(
            operation = "saml.create_service_provider",
            method = "POST",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/service-providers",
            path = path, body = payload,
        )
        return ManagementSupport.decode("saml.create_service_provider", SamlServiceProvider.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}`.
     *
     * @param spId the sp id to address
     * @return the server response
     */
    suspend fun getServiceProvider(spId: UUID): SamlServiceProvider {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.get_service_provider")
        val path = "/api/v1/tenants/${tenantId}/saml/service-providers/${spId}"
        val node = transport.send(
            operation = "saml.get_service_provider",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
            path = path,
        )
        return ManagementSupport.decode("saml.get_service_provider", SamlServiceProvider.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}`.
     *
     * A REPLACEMENT, not a patch: every field of the body is written, so read the current value
     * first and `copy()` the parts you mean to keep (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param spId the sp id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun updateServiceProvider(spId: UUID, body: SamlServiceProviderInput): SamlServiceProvider {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.update_service_provider")
        val path = "/api/v1/tenants/${tenantId}/saml/service-providers/${spId}"
        val payload = ManagementSupport.encodeBody("saml.update_service_provider", SamlServiceProviderInput.serializer(), body)
        val node = transport.send(
            operation = "saml.update_service_provider",
            method = "PUT",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("saml.update_service_provider", SamlServiceProvider.serializer(), node)
    }

    /**
     * Removes the registration and what the datastore holds for it, in one transaction. Ends no
     * session: users already signed in to the SP stay signed in there until their SP session ends.
     *
     * Issues `DELETE /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param spId the sp id to address
     */
    suspend fun deleteServiceProvider(spId: UUID) {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.delete_service_provider")
        val path = "/api/v1/tenants/${tenantId}/saml/service-providers/${spId}"
        transport.send(
            operation = "saml.delete_service_provider",
            method = "DELETE",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
            path = path,
        )
    }

    /**
     * **A parse to a draft, never a write.** Takes exactly one of `metadata_xml` and
     * `metadata_url` and returns what a registration of that SP could look like, the fingerprints
     * of the certificates it carries and warnings. A URL is fetched once, through the SSRF guard
     * (`https` only; loopback, private, link-local and cloud-metadata addresses refused; every
     * redirect hop checked); a document is refused if it holds a DTD or entity declaration, is not
     * UTF-8, is over 512 KiB, or is not exactly one `EntityDescriptor` with one SAML 2.0
     * `SPSSODescriptor`. Every refusal is a generic message that never carries the document, a
     * status line or an address. The document's own signature is not evaluated.
     *
     * Issues `POST /api/v1/tenants/{tenant_id}/saml/parse-sp-metadata`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun parseSpMetadata(body: ParseSamlSpMetadata): SamlSpMetadataDraft {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.parse_sp_metadata")
        val path = "/api/v1/tenants/${tenantId}/saml/parse-sp-metadata"
        val payload = ManagementSupport.encodeBody("saml.parse_sp_metadata", ParseSamlSpMetadata.serializer(), body)
        val node = transport.send(
            operation = "saml.parse_sp_metadata",
            method = "POST",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/parse-sp-metadata",
            path = path, body = payload,
        )
        return ManagementSupport.decode("saml.parse_sp_metadata", SamlSpMetadataDraft.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/saml/idp-credentials`.
     *
     * @return the server response
     */
    suspend fun listIdpCredentials(): List<SamlIdpCredential> {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.list_idp_credentials")
        val path = "/api/v1/tenants/${tenantId}/saml/idp-credentials"
        val node = transport.send(
            operation = "saml.list_idp_credentials",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/idp-credentials",
            path = path,
        )
        return ManagementSupport.decodeList("saml.list_idp_credentials", SamlIdpCredential.serializer(), node)
    }

    /**
     * Generates an RSA-4096 key and a leaf under `issuer_ca_id` into an **empty** slot. Takes
     * seconds. The key is sealed at rest and never returned.
     *
     * Issues `POST /api/v1/tenants/{tenant_id}/saml/idp-credentials`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun issueIdpCredential(body: IssueSamlIdpCredential): SamlIdpCredential {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.issue_idp_credential")
        val path = "/api/v1/tenants/${tenantId}/saml/idp-credentials"
        val payload = ManagementSupport.encodeBody("saml.issue_idp_credential", IssueSamlIdpCredential.serializer(), body)
        val node = transport.send(
            operation = "saml.issue_idp_credential",
            method = "POST",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/idp-credentials",
            path = path, body = payload,
        )
        return ManagementSupport.decode("saml.issue_idp_credential", SamlIdpCredential.serializer(), node)
    }

    /**
     * In **one transaction**, retires the `active` credential (its key destroyed) and makes the
     * `next` one `active`. The id must be the tenant's current `next` credential and inside its
     * validity window.
     *
     * Issues `POST /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param credentialId the credential id to address
     * @return the server response
     */
    suspend fun promoteIdpCredential(credentialId: UUID): SamlIdpCredentialPromotion {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.promote_idp_credential")
        val path = "/api/v1/tenants/${tenantId}/saml/idp-credentials/${credentialId}/promote"
        val node = transport.send(
            operation = "saml.promote_idp_credential",
            method = "POST",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote",
            path = path,
        )
        return ManagementSupport.decode("saml.promote_idp_credential", SamlIdpCredentialPromotion.serializer(), node)
    }

    /**
     * Retires a `next` or an `active` credential and destroys its key. Retiring the **`active`**
     * one with no successor stops SAML sign-on for the whole tenant at once — the incident
     * response to a leaked key. Retiring a retired credential returns it unchanged and writes no
     * audit row.
     *
     * Issues `POST /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param credentialId the credential id to address
     * @return the server response
     */
    suspend fun retireIdpCredential(credentialId: UUID): SamlIdpCredential {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "saml.retire_idp_credential")
        val path = "/api/v1/tenants/${tenantId}/saml/idp-credentials/${credentialId}/retire"
        val node = transport.send(
            operation = "saml.retire_idp_credential",
            method = "POST",
            pathTemplate = "/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire",
            path = path,
        )
        return ManagementSupport.decode("saml.retire_idp_credential", SamlIdpCredential.serializer(), node)
    }
}
