// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.ScimReconcileAccepted
import io.axiam.sdk.management.models.ScimTargetInput
import io.axiam.sdk.management.models.ScimTargetResponse
import java.util.UUID

/**
 * The scim_targets management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class ScimTargetsApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/scim-targets`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<ScimTargetResponse> {
        val path = "/api/v1/scim-targets"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "scim_targets.list",
            method = "GET",
            pathTemplate = "/api/v1/scim-targets",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("scim_targets.list", ScimTargetResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<ScimTargetResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/scim-targets`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * `credential` is required here (§31.3 rule 2). It is write-only: no response ever carries it,
     * and the SDK keeps no copy.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: ScimTargetInput): ScimTargetResponse {
        val path = "/api/v1/scim-targets"
        val payload = ManagementSupport.encodeBody("scim_targets.create", ScimTargetInput.serializer(), body)
        val node = transport.send(
            operation = "scim_targets.create",
            method = "POST",
            pathTemplate = "/api/v1/scim-targets",
            path = path, body = payload,
        )
        return ManagementSupport.decode("scim_targets.create", ScimTargetResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/scim-targets/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): ScimTargetResponse {
        val path = "/api/v1/scim-targets/${id}"
        val node = transport.send(
            operation = "scim_targets.get",
            method = "GET",
            pathTemplate = "/api/v1/scim-targets/{id}",
            path = path,
        )
        return ManagementSupport.decode("scim_targets.get", ScimTargetResponse.serializer(), node)
    }

    /**
     * A **replacement**: an omitted optional member takes its default, except the credential,
     * which absent keeps.
     *
     * Issues `PUT /api/v1/scim-targets/{id}`.
     *
     * A REPLACEMENT, not a patch: every field of the body is written, so read the current value
     * first and `copy()` the parts you mean to keep (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * **The credential is bound to its URL** (§31.3 rule 2): absent `credential` keeps the stored
     * one — except that changing `base_url` of a bearer target, `auth.token_url` or `base_url` of
     * a client-credentials target, or `auth.type`, without `credential` in the same write is
     * refused `400` and changes nothing. The SDK holds no credential to re-send. Every other
     * member left out takes its default (`ScimTargetResponse.toInput()` turns a read into the
     * body). An update overtaken by another administrator's write is `409` (§31.3 rule 4): reload,
     * then retry yourself.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(id: UUID, body: ScimTargetInput): ScimTargetResponse {
        val path = "/api/v1/scim-targets/${id}"
        val payload = ManagementSupport.encodeBody("scim_targets.update", ScimTargetInput.serializer(), body)
        val node = transport.send(
            operation = "scim_targets.update",
            method = "PUT",
            pathTemplate = "/api/v1/scim-targets/{id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("scim_targets.update", ScimTargetResponse.serializer(), node)
    }

    /**
     * The target, its link rows and its delivery state. **Nothing is deprovisioned downstream**:
     * the users and groups AXIAM created there stay.
     *
     * Issues `DELETE /api/v1/scim-targets/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * **Deprovisions nothing downstream** (§31.3 rule 8): the users and groups AXIAM created in
     * the service provider stay there, and AXIAM no longer knows them. To remove them, set
     * `deprovision` to `delete`, let AXIAM push, and only then delete the target.
     *
     * @param id the id to address
     */
    suspend fun delete(id: UUID) {
        val path = "/api/v1/scim-targets/${id}"
        transport.send(
            operation = "scim_targets.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/scim-targets/{id}",
            path = path,
        )
    }

    /**
     * Start a reconciliation now.
     *
     * Issues `POST /api/v1/scim-targets/{id}/reconcile`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * Starts a reconciliation in the background and answers `202`; its outcome is on the target's
     * `state` (§31.3 rule 7). `409` while a run holds the claim, within five minutes of the last
     * one, or for a disabled target.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun reconcile(id: UUID): ScimReconcileAccepted {
        val path = "/api/v1/scim-targets/${id}/reconcile"
        val node = transport.send(
            operation = "scim_targets.reconcile",
            method = "POST",
            pathTemplate = "/api/v1/scim-targets/{id}/reconcile",
            path = path,
        )
        return ManagementSupport.decode("scim_targets.reconcile", ScimReconcileAccepted.serializer(), node)
    }
}
