// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateScopeRequest
import io.axiam.sdk.management.models.Scope
import io.axiam.sdk.management.models.UpdateScopeRequest
import java.util.UUID

/**
 * The scopes management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class ScopesApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/resources/{resource_id}/scopes`.
     *
     * @param resourceId the resource id to address
     * @return the server response
     */
    suspend fun list(resourceId: UUID): List<Scope> {
        val path = "/api/v1/resources/${resourceId}/scopes"
        val node = transport.send(
            operation = "scopes.list",
            method = "GET",
            pathTemplate = "/api/v1/resources/{resource_id}/scopes",
            path = path,
        )
        return ManagementSupport.decodeList("scopes.list", Scope.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/resources/{resource_id}/scopes`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param resourceId the resource id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun create(resourceId: UUID, body: CreateScopeRequest): Scope {
        val path = "/api/v1/resources/${resourceId}/scopes"
        val payload = ManagementSupport.encodeBody("scopes.create", CreateScopeRequest.serializer(), body)
        val node = transport.send(
            operation = "scopes.create",
            method = "POST",
            pathTemplate = "/api/v1/resources/{resource_id}/scopes",
            path = path, body = payload,
        )
        return ManagementSupport.decode("scopes.create", Scope.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/resources/{resource_id}/scopes/{scope_id}`.
     *
     * @param resourceId the resource id to address
     * @param scopeId the scope id to address
     * @return the server response
     */
    suspend fun get(resourceId: UUID, scopeId: UUID): Scope {
        val path = "/api/v1/resources/${resourceId}/scopes/${scopeId}"
        val node = transport.send(
            operation = "scopes.get",
            method = "GET",
            pathTemplate = "/api/v1/resources/{resource_id}/scopes/{scope_id}",
            path = path,
        )
        return ManagementSupport.decode("scopes.get", Scope.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/resources/{resource_id}/scopes/{scope_id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param resourceId the resource id to address
     * @param scopeId the scope id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(resourceId: UUID, scopeId: UUID, body: UpdateScopeRequest): Scope {
        val path = "/api/v1/resources/${resourceId}/scopes/${scopeId}"
        val payload = ManagementSupport.encodeBody("scopes.update", UpdateScopeRequest.serializer(), body)
        val node = transport.send(
            operation = "scopes.update",
            method = "PUT",
            pathTemplate = "/api/v1/resources/{resource_id}/scopes/{scope_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("scopes.update", Scope.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param resourceId the resource id to address
     * @param scopeId the scope id to address
     */
    suspend fun delete(resourceId: UUID, scopeId: UUID) {
        val path = "/api/v1/resources/${resourceId}/scopes/${scopeId}"
        transport.send(
            operation = "scopes.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/resources/{resource_id}/scopes/{scope_id}",
            path = path,
        )
    }
}
