// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.BindCertificate
import io.axiam.sdk.management.models.CreateServiceAccountRequest
import io.axiam.sdk.management.models.RotateSecretResponse
import io.axiam.sdk.management.models.ServiceAccountCreatedResponse
import io.axiam.sdk.management.models.ServiceAccountResponse
import io.axiam.sdk.management.models.UpdateServiceAccount
import java.util.UUID

/**
 * The service_accounts management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class ServiceAccountsApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/service-accounts`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<ServiceAccountResponse> {
        val path = "/api/v1/service-accounts"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "service_accounts.list",
            method = "GET",
            pathTemplate = "/api/v1/service-accounts",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("service_accounts.list", ServiceAccountResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<ServiceAccountResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/service-accounts`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateServiceAccountRequest): ServiceAccountCreatedResponse {
        val path = "/api/v1/service-accounts"
        val payload = ManagementSupport.encodeBody("service_accounts.create", CreateServiceAccountRequest.serializer(), body)
        val node = transport.send(
            operation = "service_accounts.create",
            method = "POST",
            pathTemplate = "/api/v1/service-accounts",
            path = path, body = payload,
        )
        return ManagementSupport.decode("service_accounts.create", ServiceAccountCreatedResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/service-accounts/{sa_id}`.
     *
     * @param saId the sa id to address
     * @return the server response
     */
    suspend fun get(saId: UUID): ServiceAccountResponse {
        val path = "/api/v1/service-accounts/${saId}"
        val node = transport.send(
            operation = "service_accounts.get",
            method = "GET",
            pathTemplate = "/api/v1/service-accounts/{sa_id}",
            path = path,
        )
        return ManagementSupport.decode("service_accounts.get", ServiceAccountResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/service-accounts/{sa_id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param saId the sa id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(saId: UUID, body: UpdateServiceAccount): ServiceAccountResponse {
        val path = "/api/v1/service-accounts/${saId}"
        val payload = ManagementSupport.encodeBody("service_accounts.update", UpdateServiceAccount.serializer(), body)
        val node = transport.send(
            operation = "service_accounts.update",
            method = "PUT",
            pathTemplate = "/api/v1/service-accounts/{sa_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("service_accounts.update", ServiceAccountResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/service-accounts/{sa_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param saId the sa id to address
     */
    suspend fun delete(saId: UUID) {
        val path = "/api/v1/service-accounts/${saId}"
        transport.send(
            operation = "service_accounts.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/service-accounts/{sa_id}",
            path = path,
        )
    }

    /**
     * Issues `POST /api/v1/service-accounts/{sa_id}/rotate-secret`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param saId the sa id to address
     * @return the server response
     */
    suspend fun rotateSecret(saId: UUID): RotateSecretResponse {
        val path = "/api/v1/service-accounts/${saId}/rotate-secret"
        val node = transport.send(
            operation = "service_accounts.rotate_secret",
            method = "POST",
            pathTemplate = "/api/v1/service-accounts/{sa_id}/rotate-secret",
            path = path,
        )
        return ManagementSupport.decode("service_accounts.rotate_secret", RotateSecretResponse.serializer(), node)
    }

    /**
     * Issues `POST /api/v1/service-accounts/{sa_id}/bind-certificate`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param saId the sa id to address
     * @param body the request body
     */
    suspend fun bindCertificate(saId: UUID, body: BindCertificate) {
        val path = "/api/v1/service-accounts/${saId}/bind-certificate"
        val payload = ManagementSupport.encodeBody("service_accounts.bind_certificate", BindCertificate.serializer(), body)
        transport.send(
            operation = "service_accounts.bind_certificate",
            method = "POST",
            pathTemplate = "/api/v1/service-accounts/{sa_id}/bind-certificate",
            path = path, body = payload,
        )
    }
}
