// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.SecuritySettings
import io.axiam.sdk.management.models.SetOrgSettings
import io.axiam.sdk.management.models.TenantSettingsOverride
import java.util.UUID

/**
 * The settings management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class SettingsApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Returns a handle addressing [orgId] instead of the client's organization.
     *
     * A NEW handle: this one is unchanged, so a scoped call cannot leak into unrelated code
     * holding the same reference (§27.4 rule 3).
     *
     * @param orgId the organization to address
     * @return a SettingsApi scoped to [orgId]
     */
    fun inOrg(orgId: UUID): SettingsApi =
        SettingsApi(transport, scope.copy(orgId = orgId))

    /**
     * Returns a handle addressing [tenantId] instead of the client's tenant.
     *
     * A NEW handle: this one is unchanged (§27.4 rule 3).
     *
     * @param tenantId the tenant to address
     * @return a SettingsApi scoped to [tenantId]
     */
    fun forTenant(tenantId: UUID): SettingsApi =
        SettingsApi(transport, scope.copy(tenantId = tenantId))

    /**
     * Issues `GET /api/v1/organizations/{org_id}/settings`.
     *
     * @return the server response
     */
    suspend fun getOrg(): SecuritySettings {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "settings.get_org")
        val path = "/api/v1/organizations/${orgId}/settings"
        val node = transport.send(
            operation = "settings.get_org",
            method = "GET",
            pathTemplate = "/api/v1/organizations/{org_id}/settings",
            path = path,
        )
        return ManagementSupport.decode("settings.get_org", SecuritySettings.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/organizations/{org_id}/settings`.
     *
     * A REPLACEMENT, not a patch: every field of the body is written, so read the current value
     * first and `copy()` the parts you mean to keep (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun setOrg(body: SetOrgSettings): SecuritySettings {
        val orgId = ManagementSupport.resolveOrg(transport, scope, "settings.set_org")
        val path = "/api/v1/organizations/${orgId}/settings"
        val payload = ManagementSupport.encodeBody("settings.set_org", SetOrgSettings.serializer(), body)
        val node = transport.send(
            operation = "settings.set_org",
            method = "PUT",
            pathTemplate = "/api/v1/organizations/{org_id}/settings",
            path = path, body = payload,
        )
        return ManagementSupport.decode("settings.set_org", SecuritySettings.serializer(), node)
    }

    /**
     * Returns the effective (merged) security settings for the authenticated user's tenant. Org
     * baseline + tenant overrides.
     *
     * Issues `GET /api/v1/settings`.
     *
     * @return the server response
     */
    suspend fun getEffective(): SecuritySettings {
        val path = "/api/v1/settings"
        val node = transport.send(
            operation = "settings.get_effective",
            method = "GET",
            pathTemplate = "/api/v1/settings",
            path = path,
        )
        return ManagementSupport.decode("settings.get_effective", SecuritySettings.serializer(), node)
    }

    /**
     * Set tenant-level overrides. Only fields that are **more restrictive** than the org baseline
     * are accepted. Omit a field (set to `null`) to inherit from the org.
     *
     * Issues `PUT /api/v1/settings`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun setEffective(body: TenantSettingsOverride): SecuritySettings {
        val path = "/api/v1/settings"
        val payload = ManagementSupport.encodeBody("settings.set_effective", TenantSettingsOverride.serializer(), body)
        val node = transport.send(
            operation = "settings.set_effective",
            method = "PUT",
            pathTemplate = "/api/v1/settings",
            path = path, body = payload,
        )
        return ManagementSupport.decode("settings.set_effective", SecuritySettings.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/settings`.
     *
     * @return the server response
     */
    suspend fun getTenantOverride(): TenantSettingsOverride {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "settings.get_tenant_override")
        val path = "/api/v1/tenants/${tenantId}/settings"
        val node = transport.send(
            operation = "settings.get_tenant_override",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/settings",
            path = path,
        )
        return ManagementSupport.decode("settings.get_tenant_override", TenantSettingsOverride.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/tenants/{tenant_id}/settings`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun setTenantOverride(body: TenantSettingsOverride): TenantSettingsOverride {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "settings.set_tenant_override")
        val path = "/api/v1/tenants/${tenantId}/settings"
        val payload = ManagementSupport.encodeBody("settings.set_tenant_override", TenantSettingsOverride.serializer(), body)
        val node = transport.send(
            operation = "settings.set_tenant_override",
            method = "PUT",
            pathTemplate = "/api/v1/tenants/{tenant_id}/settings",
            path = path, body = payload,
        )
        return ManagementSupport.decode("settings.set_tenant_override", TenantSettingsOverride.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/tenants/{tenant_id}/settings`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     */
    suspend fun deleteTenantOverride() {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "settings.delete_tenant_override")
        val path = "/api/v1/tenants/${tenantId}/settings"
        transport.send(
            operation = "settings.delete_tenant_override",
            method = "DELETE",
            pathTemplate = "/api/v1/tenants/{tenant_id}/settings",
            path = path,
        )
    }
}
