// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.SsfStream
import io.axiam.sdk.management.models.SsfStreamInput
import java.util.UUID

/**
 * The ssf management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class SsfApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Returns a handle addressing [tenantId] instead of the client's tenant.
     *
     * A NEW handle: this one is unchanged (§27.4 rule 3).
     *
     * @param tenantId the tenant to address
     * @return a SsfApi scoped to [tenantId]
     */
    fun forTenant(tenantId: UUID): SsfApi =
        SsfApi(transport, scope.copy(tenantId = tenantId))

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/ssf/streams`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `list_streamsAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun listStreams(page: PageRequest?): Page<SsfStream> {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "ssf.list_streams")
        val path = "/api/v1/tenants/${tenantId}/ssf/streams"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "ssf.list_streams",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/ssf/streams",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("ssf.list_streams", SsfStream.serializer(), node)
    }

    /**
     * Walks `listStreams` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listStreamsAll(start: PageRequest? = null): List<SsfStream> =
        ManagementSupport.collectPages(start) { listStreams(it) }

    /**
     * Issues `POST /api/v1/tenants/{tenant_id}/ssf/streams`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun createStream(body: SsfStreamInput): SsfStream {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "ssf.create_stream")
        val path = "/api/v1/tenants/${tenantId}/ssf/streams"
        val payload = ManagementSupport.encodeBody("ssf.create_stream", SsfStreamInput.serializer(), body)
        val node = transport.send(
            operation = "ssf.create_stream",
            method = "POST",
            pathTemplate = "/api/v1/tenants/{tenant_id}/ssf/streams",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ssf.create_stream", SsfStream.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}`.
     *
     * @param streamId the stream id to address
     * @return the server response
     */
    suspend fun getStream(streamId: UUID): SsfStream {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "ssf.get_stream")
        val path = "/api/v1/tenants/${tenantId}/ssf/streams/${streamId}"
        val node = transport.send(
            operation = "ssf.get_stream",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}",
            path = path,
        )
        return ManagementSupport.decode("ssf.get_stream", SsfStream.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}`.
     *
     * A REPLACEMENT, not a patch: every field of the body is written, so read the current value
     * first and `copy()` the parts you mean to keep (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param streamId the stream id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun updateStream(streamId: UUID, body: SsfStreamInput): SsfStream {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "ssf.update_stream")
        val path = "/api/v1/tenants/${tenantId}/ssf/streams/${streamId}"
        val payload = ManagementSupport.encodeBody("ssf.update_stream", SsfStreamInput.serializer(), body)
        val node = transport.send(
            operation = "ssf.update_stream",
            method = "PUT",
            pathTemplate = "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("ssf.update_stream", SsfStream.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param streamId the stream id to address
     */
    suspend fun deleteStream(streamId: UUID) {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "ssf.delete_stream")
        val path = "/api/v1/tenants/${tenantId}/ssf/streams/${streamId}"
        transport.send(
            operation = "ssf.delete_stream",
            method = "DELETE",
            pathTemplate = "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}",
            path = path,
        )
    }
}
