// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateUserRequest
import io.axiam.sdk.management.models.MfaMethodResponse
import io.axiam.sdk.management.models.RoleAssignment
import io.axiam.sdk.management.models.UpdateUserRequest
import io.axiam.sdk.management.models.UserResponse
import java.util.UUID

/**
 * The users management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class UsersApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/users`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<UserResponse> {
        val path = "/api/v1/users"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "users.list",
            method = "GET",
            pathTemplate = "/api/v1/users",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("users.list", UserResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<UserResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Creates a user and atomically records a `terms_of_service` consent row (REQ-8 / Art. 7 proof
     * of consent). IP address and User-Agent are captured for the consent record.
     *
     * Issues `POST /api/v1/users`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateUserRequest): UserResponse {
        val path = "/api/v1/users"
        val payload = ManagementSupport.encodeBody("users.create", CreateUserRequest.serializer(), body)
        val node = transport.send(
            operation = "users.create",
            method = "POST",
            pathTemplate = "/api/v1/users",
            path = path, body = payload,
        )
        return ManagementSupport.decode("users.create", UserResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/users/{user_id}`.
     *
     * @param userId the user id to address
     * @return the server response
     */
    suspend fun get(userId: UUID): UserResponse {
        val path = "/api/v1/users/${userId}"
        val node = transport.send(
            operation = "users.get",
            method = "GET",
            pathTemplate = "/api/v1/users/{user_id}",
            path = path,
        )
        return ManagementSupport.decode("users.get", UserResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/users/{user_id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param userId the user id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(userId: UUID, body: UpdateUserRequest): UserResponse {
        val path = "/api/v1/users/${userId}"
        val payload = ManagementSupport.encodeBody("users.update", UpdateUserRequest.serializer(), body)
        val node = transport.send(
            operation = "users.update",
            method = "PUT",
            pathTemplate = "/api/v1/users/{user_id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("users.update", UserResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/users/{user_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param userId the user id to address
     */
    suspend fun delete(userId: UUID) {
        val path = "/api/v1/users/${userId}"
        transport.send(
            operation = "users.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/users/{user_id}",
            path = path,
        )
    }

    /**
     * List all MFA methods registered for a user.
     *
     * Issues `GET /api/v1/users/{user_id}/mfa-methods`.
     *
     * @param userId the user id to address
     * @return the server response
     */
    suspend fun listMfaMethods(userId: UUID): List<MfaMethodResponse> {
        val path = "/api/v1/users/${userId}/mfa-methods"
        val node = transport.send(
            operation = "users.list_mfa_methods",
            method = "GET",
            pathTemplate = "/api/v1/users/{user_id}/mfa-methods",
            path = path,
        )
        return ManagementSupport.decodeList("users.list_mfa_methods", MfaMethodResponse.serializer(), node)
    }

    /**
     * Remove a specific MFA method. Returns 400 if it is the last method and MFA is enabled.
     *
     * Issues `DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param userId the user id to address
     * @param methodId the method id to address
     */
    suspend fun deleteMfaMethod(userId: UUID, methodId: UUID) {
        val path = "/api/v1/users/${userId}/mfa-methods/${methodId}"
        transport.send(
            operation = "users.delete_mfa_method",
            method = "DELETE",
            pathTemplate = "/api/v1/users/{user_id}/mfa-methods/{method_id}",
            path = path,
        )
    }

    /**
     * Reset MFA for a user — disables MFA, clears the secret, and revokes all existing sessions.
     * Requires admin access (caller must be in the same tenant).
     *
     * Issues `POST /api/v1/users/{user_id}/reset-mfa`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param userId the user id to address
     */
    suspend fun resetMfa(userId: UUID) {
        val path = "/api/v1/users/${userId}/reset-mfa"
        transport.send(
            operation = "users.reset_mfa",
            method = "POST",
            pathTemplate = "/api/v1/users/{user_id}/reset-mfa",
            path = path,
        )
    }

    /**
     * Resets a locked user account: clears `locked_until`, resets `failed_login_attempts` to 0,
     * and sets status back to `Active`.
     *
     * Issues `POST /api/v1/users/{user_id}/unlock`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param userId the user id to address
     * @return the server response
     */
    suspend fun unlock(userId: UUID): UserResponse {
        val path = "/api/v1/users/${userId}/unlock"
        val node = transport.send(
            operation = "users.unlock",
            method = "POST",
            pathTemplate = "/api/v1/users/{user_id}/unlock",
            path = path,
        )
        return ManagementSupport.decode("users.unlock", UserResponse.serializer(), node)
    }

    /**
     * Lists a user's role assignments with the resource each is scoped to. Includes roles reaching
     * the user **through group membership**, not only the ones assigned to them directly — that is
     * what a user's effective role list is, and splitting the two would give a caller a list that
     * disagrees with the authorization decision. Anything the role detail page's members panel
     * shows as a group assignment therefore also appears here for each member.
     *
     * Issues `GET /api/v1/users/{user_id}/roles`.
     *
     * @param userId the user id to address
     * @return the server response
     */
    suspend fun listRoles(userId: UUID): List<RoleAssignment> {
        val path = "/api/v1/users/${userId}/roles"
        val node = transport.send(
            operation = "users.list_roles",
            method = "GET",
            pathTemplate = "/api/v1/users/{user_id}/roles",
            path = path,
        )
        return ManagementSupport.decodeList("users.list_roles", RoleAssignment.serializer(), node)
    }
}
