// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.ComplianceReportEntry
import io.axiam.sdk.management.models.PolicyResponse
import io.axiam.sdk.management.models.WebauthnAttestationPolicy
import java.util.UUID

/**
 * The webauthn_policy management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class WebauthnPolicyApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Returns a handle addressing [tenantId] instead of the client's tenant.
     *
     * A NEW handle: this one is unchanged (§27.4 rule 3).
     *
     * @param tenantId the tenant to address
     * @return a WebauthnPolicyApi scoped to [tenantId]
     */
    fun forTenant(tenantId: UUID): WebauthnPolicyApi =
        WebauthnPolicyApi(transport, scope.copy(tenantId = tenantId))

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`.
     *
     * @return the server response
     */
    suspend fun get(): PolicyResponse {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "webauthn_policy.get")
        val path = "/api/v1/tenants/${tenantId}/webauthn/attestation-policy"
        val node = transport.send(
            operation = "webauthn_policy.get",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
            path = path,
        )
        return ManagementSupport.decode("webauthn_policy.get", PolicyResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy`.
     *
     * A REPLACEMENT, not a patch: every field of the body is written, so read the current value
     * first and `copy()` the parts you mean to keep (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun set(body: WebauthnAttestationPolicy): WebauthnAttestationPolicy {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "webauthn_policy.set")
        val path = "/api/v1/tenants/${tenantId}/webauthn/attestation-policy"
        val payload = ManagementSupport.encodeBody("webauthn_policy.set", WebauthnAttestationPolicy.serializer(), body)
        val node = transport.send(
            operation = "webauthn_policy.set",
            method = "PUT",
            pathTemplate = "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
            path = path, body = payload,
        )
        return ManagementSupport.decode("webauthn_policy.set", WebauthnAttestationPolicy.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report`.
     *
     * @return the server response
     */
    suspend fun complianceReport(): List<ComplianceReportEntry> {
        val tenantId = ManagementSupport.resolveTenant(transport, scope, "webauthn_policy.compliance_report")
        val path = "/api/v1/tenants/${tenantId}/webauthn/compliance-report"
        val node = transport.send(
            operation = "webauthn_policy.compliance_report",
            method = "GET",
            pathTemplate = "/api/v1/tenants/{tenant_id}/webauthn/compliance-report",
            path = path,
        )
        return ManagementSupport.decodeList("webauthn_policy.compliance_report", ComplianceReportEntry.serializer(), node)
    }
}
