// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management

import io.axiam.sdk.internal.ManagementTransport
import io.axiam.sdk.management.models.CreateWebhookRequest
import io.axiam.sdk.management.models.UpdateWebhookRequest
import io.axiam.sdk.management.models.WebhookResponse
import java.util.UUID

/**
 * The webhooks management operations.
 *
 * A view over the client that created it, not a connection: constructing one performs no I/O
 * (§27.2 rule 1), so there is nothing to cache and nothing to close.
 */
class WebhooksApi internal constructor(
    private val transport: ManagementTransport,
    private val scope: NamespaceScope = NamespaceScope.inherited(),
) {

    /**
     * Issues `GET /api/v1/webhooks`.
     *
     * Paginated: `total` on the returned page is the size of the WHOLE set, not of this page
     * (§27.4 rule 4). Use `listAll(...)` to walk every page.
     *
     * @param page where to start and how many to ask for, or null for the server's default
     * @return the page of results
     */
    suspend fun list(page: PageRequest?): Page<WebhookResponse> {
        val path = "/api/v1/webhooks"
        val query = ManagementSupport.pageQuery(emptyMap(), page)
        val node = transport.send(
            operation = "webhooks.list",
            method = "GET",
            pathTemplate = "/api/v1/webhooks",
            path = path, query = query,
        )
        return ManagementSupport.decodePage("webhooks.list", WebhookResponse.serializer(), node)
    }

    /**
     * Walks `list` to exhaustion and returns every item (§27.4 rule 4).
     *
     * Stops on an empty page even when the server's `total` disagrees, so a misreporting server
     * costs one wasted request rather than an unbounded loop.
     *
     * @param start the first window to request, or null for the server's default
     * @return every item, in the server's order
     */
    suspend fun listAll(start: PageRequest? = null): List<WebhookResponse> =
        ManagementSupport.collectPages(start) { list(it) }

    /**
     * Issues `POST /api/v1/webhooks`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param body the request body
     * @return the server response
     */
    suspend fun create(body: CreateWebhookRequest): WebhookResponse {
        val path = "/api/v1/webhooks"
        val payload = ManagementSupport.encodeBody("webhooks.create", CreateWebhookRequest.serializer(), body)
        val node = transport.send(
            operation = "webhooks.create",
            method = "POST",
            pathTemplate = "/api/v1/webhooks",
            path = path, body = payload,
        )
        return ManagementSupport.decode("webhooks.create", WebhookResponse.serializer(), node)
    }

    /**
     * Issues `GET /api/v1/webhooks/{id}`.
     *
     * @param id the id to address
     * @return the server response
     */
    suspend fun get(id: UUID): WebhookResponse {
        val path = "/api/v1/webhooks/${id}"
        val node = transport.send(
            operation = "webhooks.get",
            method = "GET",
            pathTemplate = "/api/v1/webhooks/{id}",
            path = path,
        )
        return ManagementSupport.decode("webhooks.get", WebhookResponse.serializer(), node)
    }

    /**
     * Issues `PUT /api/v1/webhooks/{id}`.
     *
     * A SPARSE update: the properties you leave unset are omitted from the wire body entirely and
     * left unchanged (§27.4 rule 5).
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     * @param body the request body
     * @return the server response
     */
    suspend fun update(id: UUID, body: UpdateWebhookRequest): WebhookResponse {
        val path = "/api/v1/webhooks/${id}"
        val payload = ManagementSupport.encodeBody("webhooks.update", UpdateWebhookRequest.serializer(), body)
        val node = transport.send(
            operation = "webhooks.update",
            method = "PUT",
            pathTemplate = "/api/v1/webhooks/{id}",
            path = path, body = payload,
        )
        return ManagementSupport.decode("webhooks.update", WebhookResponse.serializer(), node)
    }

    /**
     * Issues `DELETE /api/v1/webhooks/{id}`.
     *
     * Not retried: §27.4 rule 8 makes every write on this surface single-shot, including the ones
     * that look idempotent.
     *
     * @param id the id to address
     */
    suspend fun delete(id: UUID) {
        val path = "/api/v1/webhooks/${id}"
        transport.send(
            operation = "webhooks.delete",
            method = "DELETE",
            pathTemplate = "/api/v1/webhooks/{id}",
            path = path,
        )
    }
}
