// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The AddServiceAccountMemberRequest schema from the server's OpenAPI document.
 *
 * @property serviceAccountId the server's service_account_id field
 */
@Serializable
data class AddServiceAccountMemberRequest(
    @SerialName("service_account_id") val serviceAccountId: @Serializable(with = UuidSerializer::class) UUID,
)
