// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * What attestation conveyance a registration ceremony requests, and whether the policy is enforced
 * at all. `None` is the default and reproduces today's behavior byte-for-byte: `evaluate` allows
 * every registration unconditionally, with no MDS lookup (D8 step 1).
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 */
@Serializable
enum class AttestationMode {
    @SerialName("none")
    NONE,

    @SerialName("indirect")
    INDIRECT,

    @SerialName("direct_required")
    DIRECT_REQUIRED,
}
