// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The AuditLogEntry schema from the server's OpenAPI document.
 *
 * @property action the server's action field
 * @property actorId the server's actor_id field
 * @property actorType the server's actor_type field
 * @property id the server's id field
 * @property ipAddress the server's ip_address field
 * @property metadata the server's metadata field
 * @property outcome the server's outcome field
 * @property resourceId the server's resource_id field
 * @property tenantId the server's tenant_id field
 * @property timestamp the server's timestamp field
 */
@Serializable
data class AuditLogEntry(
    @SerialName("action") val action: String,
    @SerialName("actor_id") val actorId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("actor_type") val actorType: ActorType,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("ip_address") val ipAddress: String? = null,
    @SerialName("metadata") val metadata: JsonElement,
    @SerialName("outcome") val outcome: AuditOutcome,
    @SerialName("resource_id") val resourceId: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("timestamp") val timestamp: @Serializable(with = InstantSerializer::class) Instant,
)
