// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Whether this client's authorization requests may carry OpenID Connect's authentication-request
 * parameters, or whether they are ignored (X7.1). The bundle this governs is `prompt`, `max_age`,
 * `acr_values`, `claims`, `id_token_hint`, `login_hint`, `display`, `ui_locales` and
 * `claims_locales`. It is **one** field rather than nine booleans for the same reason
 * &#91;`ClientProfile`&#93; is one field rather than a dozen: a client that honours `max_age` but
 * ignores `prompt=none` is not "mostly conformant", it is a client a relying party cannot reason
 * about. &#91;`Ignore`&#93;(Self::Ignore) is the serde default and is exactly what AXIAM has
 * always done — unknown authorization-request parameters are dropped by the query deserialiser and
 * never reach a decision. Every row written before schema v54 therefore decodes to the behaviour
 * it already had.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [AuthnRequestParamsMode.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11
 * rule 1). [UNKNOWN] is never sent: carrying it back into a write is refused locally, before any
 * request, because the SDK MUST NOT send a value it does not know (CONTRACT §34.2 P12.2) -- never
 * written as an empty string for the server to refuse. Rendering it (`toString`) never fails. A
 * `when` over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = AuthnRequestParamsMode.Companion.Serializer::class)
enum class AuthnRequestParamsMode(val wire: String) {
    IGNORE("ignore"),

    HONOUR("honour"),

    /** A value this SDK's copy of the spec does not list; never sent, see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing, and
         * refuses to encode [UNKNOWN].
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<AuthnRequestParamsMode> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.AuthnRequestParamsMode", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: AuthnRequestParamsMode) {
                if (value == UNKNOWN) {
                    throw SerializationException(
                        "AuthnRequestParamsMode.UNKNOWN is a value this SDK does not know, so it is " +
                            "never sent (CONTRACT §34.2 P12.2): replace it before writing",
                    )
                }
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): AuthnRequestParamsMode {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
