// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A CA (Certificate Authority) certificate at the organization level. CA certificates are the root
 * of trust for all tenant certificates within the organization. Private keys for signing CAs are
 * encrypted with AES-256-GCM and stored separately; non-signing CAs only store the public
 * certificate.
 *
 * @property chainPem The issuers above &#91;`Self::public_cert_pem`&#93;, concatenated PEM,
 *     nearest issuer first and the root last. `None` for a CA that is its own root, which is every
 *     CA AXIAM generated before Vault's PKI engine was an option. Present for a `vault_pki` CA,
 *     where it is the only copy of the root certificate anything outside Vault will ever see — a
 *     relying party cannot validate an AXIAM-issued leaf without it, and `root/generate/internal`
 *     returns it exactly once.
 * @property createdAt the server's created_at field
 * @property fingerprint SHA-256 fingerprint of the certificate.
 * @property id the server's id field
 * @property keyAlgorithm the server's key_algorithm field
 * @property keyCustody Which custodian holds this CA's signing key. Recorded per CA rather
 *     than read from configuration, so adopting a new custodian does not strand the CAs that
 *     already exist. Not secret — an operator needs to see it, and it discloses only where a key
 *     is kept.
 * @property keyLocator Where the custodian put the key. A Vault path under its mount; `None`
 *     for database custody, whose locator is the row itself.
 * @property mtlsTrustAnchor Whether this CA is offered as a trust anchor for mutual TLS. When
 *     set, the server exports this CA's **public** certificate to the bundle named by
 *     `AXIAM__SERVER__TLS__CLIENT_CA_BUNDLE_PATH` at startup and turns client-certificate
 *     authentication on (`optional`) if the operator has not configured it explicitly. A client
 *     presenting a certificate that chains to this CA is then verified by the TLS layer itself,
 *     which is what `axiam_pki::mtls` needs to authenticate an IoT device or a service account by
 *     certificate rather than by secret. # What is and is not copied Only `public_cert_pem` — the
 *     certificate. The **private key stays where its custodian put it** (Vault, or sealed into the
 *     row) and is never written to the server volume. A trust anchor is public by construction: it
 *     is what the server hands every client during the TLS handshake, and every device that has to
 *     validate the chain already holds a copy. # Why a restart rustls builds its `RootCertStore`
 *     once, when the listener is constructed, and actix-web binds that config for the process's
 *     life. Toggling this changes what the *next* boot trusts, and the API says so in its response
 *     rather than pretending the change took effect. Defaults to `false`, so a deployment that
 *     never touches this keeps exactly the TLS posture it has today.
 * @property notAfter Validity end.
 * @property notBefore Validity start.
 * @property organizationId The organization this CA belongs to.
 * @property parentCaId The CA in this organization that signed this one. `None` for an
 *     organization-level CA, which is either self-signed or imported and has no parent inside
 *     AXIAM.
 * @property publicCertPem PEM-encoded public certificate. The certificate that *signs*, which
 *     under `vault_pki` custody is the intermediate rather than the root beneath which it was
 *     created.
 * @property status the server's status field
 * @property subject The certificate subject (e.g., `CN=ACME Corp Root CA`).
 * @property tenantId The tenant this CA signs for, when it is a tenant signing CA. `None` for
 *     an organization-level CA — the trust anchor, and the only kind that existed before tenant
 *     signing CAs. `Some` for an intermediate created under one, which exists so a tenant's user,
 *     service and device certificates chain through a CA that can be revoked and replaced without
 *     touching the anchor the rest of the estate trusts.
 */
@Serializable
data class CaCertificate(
    @SerialName("chain_pem") val chainPem: String? = null,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("fingerprint") val fingerprint: String,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("key_algorithm") val keyAlgorithm: KeyAlgorithm,
    @SerialName("key_custody") val keyCustody: String? = null,
    @SerialName("key_locator") val keyLocator: String? = null,
    @SerialName("mtls_trust_anchor") val mtlsTrustAnchor: Boolean? = null,
    @SerialName("not_after") val notAfter: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("not_before") val notBefore: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("organization_id") val organizationId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("parent_ca_id") val parentCaId: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("public_cert_pem") val publicCertPem: String,
    @SerialName("status") val status: CertificateStatus,
    @SerialName("subject") val subject: String,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID? = null,
)
