// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A tenant-level certificate for users, services, or IoT devices. Certificates are signed by the
 * organization's CA. The private key is returned once on generation and never stored by AXIAM.
 *
 * @property certType the server's cert_type field
 * @property createdAt the server's created_at field
 * @property fingerprint SHA-256 fingerprint of the certificate.
 * @property id the server's id field
 * @property issuerCaId The CA certificate that signed this certificate.
 * @property keyAlgorithm the server's key_algorithm field
 * @property metadata Arbitrary key-value metadata (e.g., device serial, user ID binding).
 * @property notAfter Validity end.
 * @property notBefore Validity start.
 * @property publicCertPem PEM-encoded public certificate.
 * @property status the server's status field
 * @property subject The certificate subject (e.g., `CN=device-001`).
 * @property tenantId The tenant this certificate belongs to.
 */
@Serializable
data class Certificate(
    @SerialName("cert_type") val certType: CertificateType,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("fingerprint") val fingerprint: String,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("issuer_ca_id") val issuerCaId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("key_algorithm") val keyAlgorithm: KeyAlgorithm,
    @SerialName("metadata") val metadata: JsonElement,
    @SerialName("not_after") val notAfter: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("not_before") val notBefore: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("public_cert_pem") val publicCertPem: String,
    @SerialName("status") val status: CertificateStatus,
    @SerialName("subject") val subject: String,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
)
