// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Certificate issuance constraints.
 *
 * @property defaultCertValidityDays the server's default_cert_validity_days field
 * @property maxCertValidityDays the server's max_cert_validity_days field
 */
@Serializable
data class CertificatePolicy(
    @SerialName("default_cert_validity_days") val defaultCertValidityDays: Int,
    @SerialName("max_cert_validity_days") val maxCertValidityDays: Int,
)
