// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * The JWS algorithm a CIBA client signs its authentication requests with (CIBA Core §4
 * `backchannel_authentication_request_signing_alg`, §7.1.1). Exactly the three algorithms AXIAM
 * verifies on any client-signed JWT (`axiam_oauth2::jose::PERMITTED_ALGORITHMS`): FAPI 2.0
 * §5.3.1.1's list. A registration naming anything else — `RS256`, `HS256`, `none` — is refused
 * rather than stored, so no row can hold an algorithm the verifier would not honour (D-61).
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [CibaRequestSigningAlg.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11
 * rule 1). Its own wire spelling is the empty string, which no server value is: carrying an
 * unrecognised value back into an update is refused by the server rather than silently written as
 * a spelling it never used. A `when` over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = CibaRequestSigningAlg.Companion.Serializer::class)
enum class CibaRequestSigningAlg(val wire: String) {
    PS256("PS256"),

    ES256("ES256"),

    ED_DSA("EdDSA"),

    /** A value this SDK's copy of the spec does not list; see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing.
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<CibaRequestSigningAlg> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.CibaRequestSigningAlg", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: CibaRequestSigningAlg) {
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): CibaRequestSigningAlg {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
