// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Which security posture a client is registered under (X5.1). This is the FAPI "one switch". FAPI
 * 2.0 is not a single feature but a bundle of constraints — mandatory PAR, mandatory PKCE with
 * `S256`, mandatory strong client authentication, mandatory sender-constrained tokens, and a
 * refusal of every relaxation the base specs permit. Encoding them as one profile rather than a
 * dozen independent booleans means an operator cannot register a client that is *nearly* FAPI, and
 * a reviewer can answer "is this client financial-grade?" by reading one field. The same
 * philosophy as the rate-limit postures: ordinary clients see no behaviour change at all, because
 * &#91;`Standard`&#93;(Self::Standard) is the serde default and every row written before schema
 * v38 decodes to it.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 */
@Serializable
enum class ClientProfile {
    @SerialName("standard")
    STANDARD,

    @SerialName("fapi2")
    FAPI2,
}
