// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * How a client proves its identity at the token endpoint (RFC 8705 §2, OIDC Core §9 naming). Only
 * the methods AXIAM actually implements are representable. There is deliberately no `none`
 * variant: every AXIAM client is confidential today (see `handle_authorization_code`), and adding
 * a public-client value here before the rest of the server understands one would let an operator
 * register a client whose authentication is silently skipped.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [ClientAuthMethod.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11 rule
 * 1). Its own wire spelling is the empty string, which no server value is: carrying an
 * unrecognised value back into an update is refused by the server rather than silently written as
 * a spelling it never used. A `when` over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = ClientAuthMethod.Companion.Serializer::class)
enum class ClientAuthMethod(val wire: String) {
    CLIENT_SECRET_POST("client_secret_post"),

    TLS_CLIENT_AUTH("tls_client_auth"),

    SELF_SIGNED_TLS_CLIENT_AUTH("self_signed_tls_client_auth"),

    PRIVATE_KEY_JWT("private_key_jwt"),

    /** A value this SDK's copy of the spec does not list; see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing.
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<ClientAuthMethod> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.ClientAuthMethod", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: ClientAuthMethod) {
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): ClientAuthMethod {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
