// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * How a client proves its identity at the token endpoint (RFC 8705 §2, OIDC Core §9 naming). Only
 * the methods AXIAM actually implements are representable. There is deliberately no `none`
 * variant: every AXIAM client is confidential today (see `handle_authorization_code`), and adding
 * a public-client value here before the rest of the server understands one would let an operator
 * register a client whose authentication is silently skipped.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 */
@Serializable
enum class ClientAuthMethod {
    @SerialName("client_secret_post")
    CLIENT_SECRET_POST,

    @SerialName("tls_client_auth")
    TLS_CLIENT_AUTH,

    @SerialName("self_signed_tls_client_auth")
    SELF_SIGNED_TLS_CLIENT_AUTH,

    @SerialName("private_key_jwt")
    PRIVATE_KEY_JWT,
}
