// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * One credential's compliance outcome (D9).
 *
 * @property aaguid the server's aaguid field
 * @property authenticatorName the server's authenticator_name field
 * @property compliant `false` only for a genuine policy violation
 *     (&#91;`ComplianceStatus::NonCompliant`&#93;) — a credential with no recorded AAGUID
 *     (&#91;`ComplianceStatus::Unknown`&#93;, D9's pre-X3 case) is always `true` here, never
 *     reported as a violation.
 * @property credentialId the server's credential_id field
 * @property name The credential's user-assigned name (`WebauthnCredential::name`), not the
 *     owning user's account name.
 * @property reason `None` only when `compliant` and the credential has a recorded AAGUID; set
 *     for every non-compliant *and* every "unknown" (pre-X3) credential.
 * @property userId the server's user_id field
 */
@Serializable
data class ComplianceReportEntry(
    @SerialName("aaguid") val aaguid: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("authenticator_name") val authenticatorName: String? = null,
    @SerialName("compliant") val compliant: Boolean,
    @SerialName("credential_id") val credentialId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("name") val name: String,
    @SerialName("reason") val reason: String? = null,
    @SerialName("user_id") val userId: @Serializable(with = UuidSerializer::class) UUID,
)
