// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request body for &#91;`create_registration_token`&#93;.
 *
 * @property expiresInHours Lifetime in hours. Defaults to 24 and is refused above 168 (a week)
 *     — see `axiam_core::models::oauth2_registration_token`.
 * @property name Operator-facing label, e.g. `"mcp-inspector-demo"`, so a tenant with several
 *     outstanding tokens can tell them apart.
 */
@Serializable
data class CreateRegistrationTokenRequest(
    @SerialName("expires_in_hours") val expiresInHours: Int? = null,
    @SerialName("name") val name: String,
)
