// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Body of `POST .../tenants/{tenant_id}/signing-cas`.
 *
 * @property keyAlgorithm the server's key_algorithm field
 * @property parentCaId The organization CA that signs it.
 * @property subject Subject for the signing CA, e.g. `CN=ACME R&D Signing CA`.
 * @property validityDays Validity duration in days, capped to the parent's own expiry.
 */
@Serializable
data class CreateIntermediateCaRequest(
    @SerialName("key_algorithm") val keyAlgorithm: KeyAlgorithm,
    @SerialName("parent_ca_id") val parentCaId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("subject") val subject: String,
    @SerialName("validity_days") val validityDays: Int,
)
