// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The CreateOAuth2ClientRequest schema from the server's OpenAPI document.
 *
 * @property backchannelLogoutUri B5 — where OIDC back-channel logout tokens are delivered.
 *     Omit for a client that does not participate.
 * @property dpopBoundAccessTokens RFC 9449 §5.2 — issue DPoP-bound (sender-constrained) access
 *     tokens to this client. Independent of both the authentication method and
 *     `tls_client_certificate_bound_access_tokens`; a client may ask for both constraints, and a
 *     token carrying both must satisfy both.
 * @property dpopRequireNonce RFC 9449 §8 — require this client's DPoP proofs to carry a
 *     server-issued nonce. **Not implemented in this build (SEC-097).** `true` is refused with
 *     `400`; only `false` (the default) is accepted. Nothing reads the stored value, so accepting
 *     `true` would persist and echo back a security switch that does nothing. DPoP proofs are made
 *     single-use at the token endpoint by `jti` replay detection instead — see
 *     `docs/security-profiles.md`.
 * @property grantTypes Grant types this client is authorized to use.
 * @property jwks RFC 7591 §2 — the client's public key set, inline, for `private_key_jwt`.
 *     Exactly one of `jwks` and `jwks_uri` may be set.
 * @property jwksUri RFC 7591 §2 — where the client publishes its public key set. Must be an
 *     absolute `https` URL, and is fetched through the SSRF-guarded JWKS cache, which refuses
 *     private and loopback addresses.
 * @property name Human-readable name for the client.
 * @property postLogoutRedirectUris B5 — allow-list for RP-initiated logout's
 *     `post_logout_redirect_uri`. Separate from `redirect_uris` on purpose: that list receives
 *     authorization codes, this one receives a browser after logout.
 * @property profile X5.1 — the security posture this client is registered under. `"standard"`
 *     (the default) is every AXIAM client that has ever existed. `"fapi2"` turns on the whole FAPI
 *     2.0 constraint bundle at once, and the registration is refused unless it also sets
 *     `require_par`, a strong `token_endpoint_auth_method` (either mTLS method or
 *     `private_key_jwt`), and at least one sender-constraining mechanism
 *     (`tls_client_certificate_bound_access_tokens` or `dpop_bound_access_tokens`). See the FAPI
 *     operator guide.
 * @property redirectUris Allowed redirect URIs (must be HTTPS, except localhost for dev).
 *     SEC-089: this list doubles as the token-exchange audience allow-list — adding a URI here
 *     also authorises it as a token audience for this client, so review additions on
 *     exchange-capable clients with that in mind (see `docs/api/token-exchange.md#audience`).
 * @property requirePar B5 — require this client to push its authorization parameters to
 *     `/oauth2/par` (RFC 9126) rather than sending them through the browser.
 * @property scopes Scopes the client may request.
 * @property selfSignedTlsClientAuthThumbprints Accepted certificate thumbprints for
 *     `self_signed_tls_client_auth`, as base64url-unpadded SHA-256 digests of the DER certificate
 *     (the same `x5t#S256` encoding as the `cnf` claim). More than one permits an overlapping
 *     rotation.
 * @property tlsClientAuthSanDns RFC 8705 §2.1.2 — expected `dNSName` SAN.
 * @property tlsClientAuthSanUri RFC 8705 §2.1.2 — expected `uniformResourceIdentifier` SAN.
 * @property tlsClientAuthSubjectDn RFC 8705 §2.1.2 — expected certificate subject DN, RFC 4514
 *     form. Exactly one of the three `tls_client_auth_*` parameters may be set.
 * @property tlsClientCertificateBoundAccessTokens RFC 8705 §3.4 — issue certificate-bound
 *     (sender-constrained) access tokens to this client. Independent of the authentication method.
 * @property tokenEndpointAuthMethod X5.1 — how this client authenticates at the token endpoint
 *     (RFC 8705 §2). Defaults to `client_secret_post`.
 */
@Serializable
data class CreateOAuth2ClientRequest(
    @SerialName("backchannel_logout_uri") val backchannelLogoutUri: String? = null,
    @SerialName("dpop_bound_access_tokens") val dpopBoundAccessTokens: Boolean? = null,
    @SerialName("dpop_require_nonce") val dpopRequireNonce: Boolean? = null,
    @SerialName("grant_types") val grantTypes: List<String>,
    @SerialName("jwks") val jwks: String? = null,
    @SerialName("jwks_uri") val jwksUri: String? = null,
    @SerialName("name") val name: String,
    @SerialName("post_logout_redirect_uris") val postLogoutRedirectUris: List<String>? = null,
    @SerialName("profile") val profile: ClientProfile? = null,
    @SerialName("redirect_uris") val redirectUris: List<String>,
    @SerialName("require_par") val requirePar: Boolean? = null,
    @SerialName("scopes") val scopes: List<String>,
    @SerialName("self_signed_tls_client_auth_thumbprints") val selfSignedTlsClientAuthThumbprints: List<String>? = null,
    @SerialName("tls_client_auth_san_dns") val tlsClientAuthSanDns: String? = null,
    @SerialName("tls_client_auth_san_uri") val tlsClientAuthSanUri: String? = null,
    @SerialName("tls_client_auth_subject_dn") val tlsClientAuthSubjectDn: String? = null,
    @SerialName("tls_client_certificate_bound_access_tokens") val tlsClientCertificateBoundAccessTokens: Boolean? = null,
    @SerialName("token_endpoint_auth_method") val tokenEndpointAuthMethod: ClientAuthMethod? = null,
)
