// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The CreateFederationConfigRequest schema from the server's OpenAPI document.
 *
 * @property allowedAlgorithms Accepted JWT signing algorithms (OIDC) or signature algorithms
 *     (SAML). Defaults to `&#91;"RS256"&#93;` when not provided (CQ-B40/REQ-14 AC-5).
 * @property attributeMap Maps external IdP attributes to AXIAM user fields.
 * @property clientId OAuth2 client ID registered with the external IdP.
 * @property clientSecret OAuth2 client secret registered with the external IdP. -- SECRET:
 *     redacted from toString and from every rendering except the one request body it is sent in
 * @property idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML assertions or
 *     OIDC signatures (CQ-B40/REQ-14 AC-5). Required for SAML configs.
 * @property metadataUrl OIDC discovery URL or SAML metadata URL.
 * @property protocol Federation protocol: "OidcConnect" or "Saml".
 * @property provider Display name for the identity provider (e.g., "Google", "Okta").
 * @property tokenExchange the server's token_exchange field
 */
@Serializable
data class CreateFederationConfigRequest(
    @SerialName("allowed_algorithms") val allowedAlgorithms: List<String>? = null,
    @SerialName("attribute_map") val attributeMap: JsonElement? = null,
    @SerialName("client_id") val clientId: String,
    @SerialName("client_secret") val clientSecret: @Contextual Sensitive<String>,
    @SerialName("idp_signing_cert_pem") val idpSigningCertPem: String? = null,
    @SerialName("metadata_url") val metadataUrl: String? = null,
    @SerialName("protocol") val protocol: String,
    @SerialName("provider") val provider: String,
    @SerialName("token_exchange") val tokenExchange: TokenExchangeTrustRequest? = null,
)
