// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The CreatePgpKeyRequest schema from the server's OpenAPI document.
 *
 * @property algorithm the server's algorithm field
 * @property email Email for the OpenPGP User ID.
 * @property name the server's name field
 * @property purpose the server's purpose field
 */
@Serializable
data class CreatePgpKeyRequest(
    @SerialName("algorithm") val algorithm: PgpKeyAlgorithm,
    @SerialName("email") val email: String,
    @SerialName("name") val name: String,
    @SerialName("purpose") val purpose: PgpKeyPurpose,
)
