// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The CreateServiceAccountRequest schema from the server's OpenAPI document.
 *
 * @property description Optional human-readable description of the account's purpose.
 * @property name the server's name field
 */
@Serializable
data class CreateServiceAccountRequest(
    @SerialName("description") val description: String? = null,
    @SerialName("name") val name: String,
)
