// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The CreateReactorRequest schema from the server's OpenAPI document.
 *
 * @property description the server's description field
 * @property enabled the server's enabled field
 * @property events Event names from the registry (`GET /api/v1/reactors/events`).
 * @property failurePolicy the server's failure_policy field
 * @property mode the server's mode field
 * @property name the server's name field
 * @property priority the server's priority field
 * @property timeoutMs Omit to take the 500 ms default. Capped at 5 000 ms.
 */
@Serializable
data class CreateReactorRequest(
    @SerialName("description") val description: String? = null,
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("events") val events: List<String>,
    @SerialName("failure_policy") val failurePolicy: FailurePolicy? = null,
    @SerialName("mode") val mode: ReactorMode,
    @SerialName("name") val name: String,
    @SerialName("priority") val priority: Int? = null,
    @SerialName("timeout_ms") val timeoutMs: Int? = null,
)
