// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The CreateNotificationRuleRequest schema from the server's OpenAPI document.
 *
 * @property description Description of what this rule monitors.
 * @property events Event types that trigger this rule.
 * @property name Human-readable name for the rule.
 * @property recipientEmails Email addresses to notify.
 */
@Serializable
data class CreateNotificationRuleRequest(
    @SerialName("description") val description: String,
    @SerialName("events") val events: List<NotificationEventType>,
    @SerialName("name") val name: String,
    @SerialName("recipient_emails") val recipientEmails: List<String>,
)
