// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The one-time reveal. Same shape as service-account creation: the secret is returned once and
 * only its hash is kept.
 *
 * @property createdAt the server's created_at field
 * @property createdBy the server's created_by field
 * @property expiresAt the server's expires_at field
 * @property id the server's id field
 * @property lastUsedAt the server's last_used_at field
 * @property name the server's name field
 * @property provisioningToken The plaintext handle — shown once, never retrievable again. --
 *     SECRET: redacted from toString and from every rendering except the one request body it is
 *     sent in
 * @property revokedAt the server's revoked_at field
 * @property status the server's status field
 * @property tenantId the server's tenant_id field
 * @property userId the server's user_id field
 */
@Serializable
data class CreateScimTokenResponse(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("created_by") val createdBy: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("expires_at") val expiresAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("last_used_at") val lastUsedAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("name") val name: String,
    @SerialName("provisioning_token") val provisioningToken: @Contextual Sensitive<String>,
    @SerialName("revoked_at") val revokedAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("status") val status: ScimTokenStatus,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("user_id") val userId: @Serializable(with = UuidSerializer::class) UUID,
)
