// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The CreateCertificateRequest schema from the server's OpenAPI document.
 *
 * @property certType the server's cert_type field
 * @property issuerCaId the server's issuer_ca_id field
 * @property keyAlgorithm the server's key_algorithm field
 * @property metadata the server's metadata field
 * @property subject the server's subject field
 * @property validityDays Validity duration in days.
 */
@Serializable
data class CreateCertificateRequest(
    @SerialName("cert_type") val certType: CertificateType,
    @SerialName("issuer_ca_id") val issuerCaId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("key_algorithm") val keyAlgorithm: KeyAlgorithm,
    @SerialName("metadata") val metadata: JsonElement? = null,
    @SerialName("subject") val subject: String,
    @SerialName("validity_days") val validityDays: Int,
)
