// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The CreateGroupRequest schema from the server's OpenAPI document.
 *
 * @property description the server's description field
 * @property metadata the server's metadata field
 * @property name the server's name field
 */
@Serializable
data class CreateGroupRequest(
    @SerialName("description") val description: String,
    @SerialName("metadata") val metadata: JsonElement? = null,
    @SerialName("name") val name: String,
)
