// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import java.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A read-only view of the sync job's state for one tenant. Counts of what a run did are in its
 * audit rows, and no account id is here.
 *
 * @property fullRequired The next run must be a full reconciliation.
 * @property hasWatermark An incremental run has a starting point.
 * @property lastAttemptAt When the last attempt started, or null before the first run.
 * @property lastFullRunAt When the last complete full run finished, or null.
 * @property lastResult `ok`, `partial`, `failed` or `safety_valve` (an open set: decode
 *     another value without failing), or null before the first run.
 */
@Serializable
data class DirectorySyncStatus(
    @SerialName("full_required") val fullRequired: Boolean,
    @SerialName("has_watermark") val hasWatermark: Boolean,
    @SerialName("last_attempt_at") val lastAttemptAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("last_full_run_at") val lastFullRunAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("last_result") val lastResult: String? = null,
)
