// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A tenant's directory configuration, as stored and as read back. Carries no secret: see the
 * module documentation.
 *
 * @property baseDn Where users are searched for.
 * @property bindDn The service account AXIAM binds as to search. It should hold read-only
 *     rights: AXIAM never writes to a directory.
 * @property createdAt When the row was created.
 * @property enabled Whether the directory is used for sign-in and sync.
 * @property groupBaseDn Where groups are searched for (reverse-`member` lookups, group sync).
 * @property groupFilter Restricts which entries under &#91;`Self::group_base_dn`&#93; are
 *     groups.
 * @property groupMappings The group-mapping table (D-30): which directory groups put a user
 *     into which AXIAM groups. Empty means no directory group maps to anything, and a sign-in then
 *     removes every directory-sourced membership the user held.
 * @property groupMemberAttribute `memberOf` (user-side, AD) or `member` (group-side,
 *     OpenLDAP).
 * @property groupNestingDepth How many levels of nested groups are followed, `0..=10`.
 * @property id Row identifier.
 * @property jitProvisioning Provision an AXIAM user on first successful directory sign-in.
 * @property kind The kind of directory, which selects defaults.
 * @property startTls Upgrade an `ldap://` connection with StartTLS before any bind.
 * @property syncIntervalSecs Seconds between incremental sync runs.
 * @property tenantId The owning tenant. At most one configuration exists per tenant.
 * @property trustAnchorsPem PEM CA certificates that anchor trust in the directory's server
 *     certificate. Empty means the platform roots used by the rest of the workspace's outbound
 *     TLS. An organisation CA's PEM can be pasted here.
 * @property updatedAt When the row was last written.
 * @property url `ldaps://host&#91;:port&#93;` or `ldap://host&#91;:port&#93;` together with
 *     &#91;`Self::start_tls`&#93;. A plaintext URL is refused at configuration time.
 * @property userAttributeMap Which attribute feeds which user field.
 * @property userFilter The user-lookup filter template. It contains exactly one `{username}`
 *     placeholder, which the bind path replaces with the RFC 4515-escaped login name; the template
 *     itself is never formatted with raw input.
 */
@Serializable
data class DirectoryConfig(
    @SerialName("base_dn") val baseDn: String,
    @SerialName("bind_dn") val bindDn: String,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("group_base_dn") val groupBaseDn: String? = null,
    @SerialName("group_filter") val groupFilter: String? = null,
    @SerialName("group_mappings") val groupMappings: List<GroupMapping>,
    @SerialName("group_member_attribute") val groupMemberAttribute: String,
    @SerialName("group_nesting_depth") val groupNestingDepth: Int,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("jit_provisioning") val jitProvisioning: Boolean,
    @SerialName("kind") val kind: DirectoryKind,
    @SerialName("start_tls") val startTls: Boolean,
    @SerialName("sync_interval_secs") val syncIntervalSecs: Long,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("trust_anchors_pem") val trustAnchorsPem: List<String>,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("url") val url: String,
    @SerialName("user_attribute_map") val userAttributeMap: UserAttributeMap,
    @SerialName("user_filter") val userFilter: String,
)
