// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Partial tenant overrides for email configuration. `None` = inherit from org baseline.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property enabled the server's enabled field
 * @property fromEmail the server's from_email field
 * @property fromName the server's from_name field
 * @property provider the server's provider field
 * @property replyTo `Some(None)` explicitly clears reply-to; `None` inherits.
 */
@Serializable
data class EmailConfigOverride(
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("from_email") val fromEmail: String? = null,
    @SerialName("from_name") val fromName: String? = null,
    @SerialName("provider") val provider: ProviderConfig? = null,
    @SerialName("reply_to") val replyTo: String? = null,
)
