// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * What the server does when an interceptor does not produce a usable reply — timeout, transport
 * failure, bad signature, stale nonce, or a patch the allow-list rejects.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 */
@Serializable
enum class FailurePolicy {
    @SerialName("fail_closed")
    FAIL_CLOSED,

    @SerialName("fail_open")
    FAIL_OPEN,
}
