// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * What the server does when an interceptor does not produce a usable reply — timeout, transport
 * failure, bad signature, stale nonce, or a patch the allow-list rejects.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [FailurePolicy.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11 rule 1).
 * [UNKNOWN] is never sent: carrying it back into a write is refused locally, before any request,
 * because the SDK MUST NOT send a value it does not know (CONTRACT §34.2 P12.2) -- never written
 * as an empty string for the server to refuse. Rendering it (`toString`) never fails. A `when`
 * over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = FailurePolicy.Companion.Serializer::class)
enum class FailurePolicy(val wire: String) {
    FAIL_CLOSED("fail_closed"),

    FAIL_OPEN("fail_open"),

    /** A value this SDK's copy of the spec does not list; never sent, see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing, and
         * refuses to encode [UNKNOWN].
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<FailurePolicy> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.FailurePolicy", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: FailurePolicy) {
                if (value == UNKNOWN) {
                    throw SerializationException(
                        "FailurePolicy.UNKNOWN is a value this SDK does not know, so it is " +
                            "never sent (CONTRACT §34.2 P12.2): replace it before writing",
                    )
                }
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): FailurePolicy {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
