// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The FederationLinkResponse schema from the server's OpenAPI document.
 *
 * @property createdAt the server's created_at field
 * @property externalEmail the server's external_email field
 * @property externalSubject the server's external_subject field
 * @property federationConfigId the server's federation_config_id field
 * @property id the server's id field
 * @property tenantId the server's tenant_id field
 * @property updatedAt the server's updated_at field
 * @property userId the server's user_id field
 */
@Serializable
data class FederationLinkResponse(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("external_email") val externalEmail: String? = null,
    @SerialName("external_subject") val externalSubject: String,
    @SerialName("federation_config_id") val federationConfigId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("user_id") val userId: @Serializable(with = UuidSerializer::class) UUID,
)
