// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Federation config response -- omits client_secret.
 *
 * @property attributeMap the server's attribute_map field
 * @property clientId the server's client_id field
 * @property createdAt the server's created_at field
 * @property enabled the server's enabled field
 * @property id the server's id field
 * @property metadataUrl the server's metadata_url field
 * @property protocol the server's protocol field
 * @property provider the server's provider field
 * @property tenantId the server's tenant_id field
 * @property tokenExchange X4 external token-exchange trust.
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class FederationConfigResponse(
    @SerialName("attribute_map") val attributeMap: JsonElement,
    @SerialName("client_id") val clientId: String,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("metadata_url") val metadataUrl: String? = null,
    @SerialName("protocol") val protocol: String,
    @SerialName("provider") val provider: String,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("token_exchange") val tokenExchange: TokenExchangeTrustResponse,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
