// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Body for recording an OIDC scope-release consent.
 *
 * @property clientId The relying party the claims would be released to.
 * @property scopes The sensitive scopes being consented to. Order does not matter; the record
 *     is written in the canonical order so that the same consent has one name.
 */
@Serializable
data class GrantScopeConsent(
    @SerialName("client_id") val clientId: String,
    @SerialName("scopes") val scopes: List<String>,
)
