// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * One row of the group-mapping table (G-3, T23.3.4, D-30): a directory group, named by its
 * distinguished name, and the AXIAM group a member of it is put into. **The table is the only way
 * a directory group reaches an AXIAM group.** There is no match by name, no prefix or wildcard,
 * and no AXIAM group is ever created from a directory one: a directory administrator who names a
 * group `admins` gains nothing unless a tenant administrator mapped it here. The DN is stored as
 * the administrator typed it and compared after RFC 4514 normalisation (`axiam_directory::dn`), so
 * `CN=Staff, OU=Groups` and `cn=staff,ou=groups` are the same row. One DN may map to several AXIAM
 * groups; the same (DN, group) pair twice is refused as redundant.
 *
 * @property directoryGroupDn The directory group's distinguished name.
 * @property groupId The AXIAM group of the same tenant a member of that directory group is put
 *     into. Checked to exist in the tenant when the configuration is written.
 */
@Serializable
data class GroupMapping(
    @SerialName("directory_group_dn") val directoryGroupDn: String,
    @SerialName("group_id") val groupId: @Serializable(with = UuidSerializer::class) UUID,
)
