// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `POST …/saml/idp-credentials` body.
 *
 * @property issuerCaId An active signing CA the caller may issue from.
 * @property slot The slot to fill; it must be empty.
 * @property validityDays 1 to 730, default 365; never beyond the CA's own expiry.
 */
@Serializable
data class IssueSamlIdpCredential(
    @SerialName("issuer_ca_id") val issuerCaId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("slot") val slot: SamlIdpSlot,
    @SerialName("validity_days") val validityDays: Long? = null,
)
