// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The type of key algorithm used for a certificate.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 */
@Serializable
enum class KeyAlgorithm {
    @SerialName("Rsa4096")
    RSA4096,

    @SerialName("Ed25519")
    ED25519,
}
