// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `POST /api/v1/tenants/{tenant_id}/directory/links` body.
 *
 * @property userId The local account to link. The directory entry is found by the directory,
 *     from the account's own username; the caller names no entry.
 */
@Serializable
data class LinkDirectoryAccount(
    @SerialName("user_id") val userId: @Serializable(with = UuidSerializer::class) UUID,
)
