// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Account lockout rules.
 *
 * @property lockoutBackoffMultiplier the server's lockout_backoff_multiplier field
 * @property lockoutDurationSecs the server's lockout_duration_secs field
 * @property maxFailedLoginAttempts the server's max_failed_login_attempts field
 * @property maxLockoutDurationSecs the server's max_lockout_duration_secs field
 */
@Serializable
data class LockoutPolicy(
    @SerialName("lockout_backoff_multiplier") val lockoutBackoffMultiplier: Double,
    @SerialName("lockout_duration_secs") val lockoutDurationSecs: Long,
    @SerialName("max_failed_login_attempts") val maxFailedLoginAttempts: Int,
    @SerialName("max_lockout_duration_secs") val maxLockoutDurationSecs: Long,
)
