// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Who created a client registration (D5, T21.4). The discriminator that separates a registration
 * an administrator made from one that arrived over an open endpoint. Three things read it and each
 * would otherwise have to infer provenance from something that is not provenance: *
 * `axiam_oauth2::fapi` refuses a FAPI profile on anything but &#91;`Admin`&#93;(Self::Admin) (I5)
 * — a client nobody vetted cannot be financial-grade; * the authorization endpoint forces a
 * consent hop for every other value (D4) — an unrelated party gets a question put to the end user,
 * whatever scopes it asked for; * the T21.4 sweeper deletes only &#91;`Dcr`&#93;(Self::Dcr) rows,
 * so an administrator's client is never swept however long it sits unused.
 * &#91;`Admin`&#93;(Self::Admin) is the serde default and therefore what every row written before
 * T21.4 decodes to, which is the truth: they were all created through `POST /oauth2-clients` by
 * somebody holding `oauth2_clients:create`.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [ManagedBy.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11 rule 1). Its
 * own wire spelling is the empty string, which no server value is: carrying an unrecognised value
 * back into an update is refused by the server rather than silently written as a spelling it never
 * used. A `when` over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = ManagedBy.Companion.Serializer::class)
enum class ManagedBy(val wire: String) {
    ADMIN("admin"),

    DCR("dcr"),

    CIMD("cimd"),

    /** A value this SDK's copy of the spec does not list; see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing.
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<ManagedBy> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.ManagedBy", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: ManagedBy) {
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): ManagedBy {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
