// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The 'replaced' arm of MdsRefreshOutcome.
 *
 * @property entryCount the server's entry_count field
 * @property no the server's no field
 */
@Serializable
@SerialName("replaced")
data class MdsRefreshOutcomeReplaced(
    @SerialName("entry_count") val entryCount: Int,
    @SerialName("no") val no: Long,
) : MdsRefreshOutcome
