// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * `POST /api/v1/mds/refresh` response — the outcome of one ingestion attempt (mirrors
 * `axiam_db::mds_ingest::MdsIngestOutcome`).
 *
 * A closed set of shapes discriminated by the outcome field. Sealed, so a `when` over the
 * permitted arms is exhaustive and the compiler says so — which is what makes adding an arm a
 * compile error at every call site rather than a silent fall-through.
 */
@Serializable
@JsonClassDiscriminator("outcome")
sealed interface MdsRefreshOutcome
