// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import java.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `GET /api/v1/mds/status` response. `no`/`next_update`/`last_refreshed_at` are `None` and `stale`
 * is `false` when MDS has never been ingested — a meaningful, valid answer ("nothing ingested
 * yet"), not an error.
 *
 * @property entryCount the server's entry_count field
 * @property lastRefreshedAt the server's last_refreshed_at field
 * @property nextUpdate the server's next_update field
 * @property no the server's no field
 * @property stale the server's stale field
 */
@Serializable
data class MdsStatusResponse(
    @SerialName("entry_count") val entryCount: Long,
    @SerialName("last_refreshed_at") val lastRefreshedAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("next_update") val nextUpdate: String? = null,
    @SerialName("no") val no: Long? = null,
    @SerialName("stale") val stale: Boolean,
)
