// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The MfaMethodResponse schema from the server's OpenAPI document.
 *
 * @property createdAt the server's created_at field
 * @property lastUsedAt the server's last_used_at field
 * @property methodId the server's method_id field
 * @property methodType the server's method_type field
 * @property name the server's name field
 */
@Serializable
data class MfaMethodResponse(
    @SerialName("created_at") val createdAt: String,
    @SerialName("last_used_at") val lastUsedAt: String? = null,
    @SerialName("method_id") val methodId: String,
    @SerialName("method_type") val methodType: MfaMethodType,
    @SerialName("name") val name: String,
)
