// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The acknowledgement, which is mostly about the restart.
 *
 * @property caCertificateId The CA this is about.
 * @property message A sentence an operator can act on, rather than a bare boolean.
 * @property mtlsTrustAnchor The flag as now stored.
 * @property restartRequired Always `true`: rustls builds its client trust store once, when the
 *     listener is constructed, so this takes effect at the next start.
 */
@Serializable
data class MtlsTrustAnchorResponse(
    @SerialName("ca_certificate_id") val caCertificateId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("message") val message: String,
    @SerialName("mtls_trust_anchor") val mtlsTrustAnchor: Boolean,
    @SerialName("restart_required") val restartRequired: Boolean,
)
