// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The acknowledgement, which is mostly about the restart.
 *
 * @property caCertificateId The CA this is about.
 * @property message A sentence an operator can act on, rather than a bare boolean.
 * @property mtlsTrustAnchor The flag as now stored.
 * @property restartRequired Whether the change still needs a restart to take effect. `false`
 *     when the live listener accepted the new anchor set — the ordinary case on a TLS deployment.
 *     `true` only when there was no listener to reload into (plaintext, or `client_auth = off`),
 *     where the flag is stored and applies at the next start.
 * @property trustedAnchors How many CAs the listener now trusts for client authentication,
 *     when it was reloaded. `None` when nothing was reloaded.
 */
@Serializable
data class MtlsTrustAnchorResponse(
    @SerialName("ca_certificate_id") val caCertificateId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("message") val message: String,
    @SerialName("mtls_trust_anchor") val mtlsTrustAnchor: Boolean,
    @SerialName("restart_required") val restartRequired: Boolean,
    @SerialName("trusted_anchors") val trustedAnchors: Int? = null,
)
