// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Admin notification preferences.
 *
 * @property adminNotificationsEnabled the server's admin_notifications_enabled field
 */
@Serializable
data class NotificationPolicy(
    @SerialName("admin_notifications_enabled") val adminNotificationsEnabled: Boolean,
)
