// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response for client creation -- includes the one-time plaintext secret.
 *
 * @property clientId the server's client_id field
 * @property clientSecret the server's client_secret field -- SECRET: redacted from toString
 *     and from every rendering except the one request body it is sent in
 * @property createdAt the server's created_at field
 * @property grantTypes the server's grant_types field
 * @property id the server's id field
 * @property name the server's name field
 * @property redirectUris the server's redirect_uris field
 * @property scopes the server's scopes field
 * @property tenantId the server's tenant_id field
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class OAuth2ClientCreatedResponse(
    @SerialName("client_id") val clientId: String,
    @SerialName("client_secret") val clientSecret: @Contextual Sensitive<String>,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("grant_types") val grantTypes: List<String>,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("name") val name: String,
    @SerialName("redirect_uris") val redirectUris: List<String>,
    @SerialName("scopes") val scopes: List<String>,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
