// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OAuth2 client response -- omits client_secret_hash.
 *
 * @property clientId the server's client_id field
 * @property createdAt the server's created_at field
 * @property dpopBoundAccessTokens the server's dpop_bound_access_tokens field
 * @property dpopRequireNonce the server's dpop_require_nonce field
 * @property grantTypes the server's grant_types field
 * @property id the server's id field
 * @property jwks X5.1 — echoed so an operator can confirm which key source is registered. The
 *     document itself is public key material, so returning it leaks nothing; a `jwks_uri` is
 *     likewise public by construction.
 * @property jwksUri the server's jwks_uri field
 * @property name the server's name field
 * @property profile X5.1 — the registered posture and mTLS credentials. Read-back matters: an
 *     operator auditing which clients are financial-grade should be able to answer it from this
 *     endpoint rather than from the database.
 * @property redirectUris the server's redirect_uris field
 * @property requirePar the server's require_par field
 * @property scopes the server's scopes field
 * @property selfSignedTlsClientAuthThumbprints the server's
 *     self_signed_tls_client_auth_thumbprints field
 * @property tenantId the server's tenant_id field
 * @property tlsClientAuthSanDns the server's tls_client_auth_san_dns field
 * @property tlsClientAuthSanUri the server's tls_client_auth_san_uri field
 * @property tlsClientAuthSubjectDn the server's tls_client_auth_subject_dn field
 * @property tlsClientCertificateBoundAccessTokens the server's
 *     tls_client_certificate_bound_access_tokens field
 * @property tokenEndpointAuthMethod the server's token_endpoint_auth_method field
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class OAuth2ClientResponse(
    @SerialName("client_id") val clientId: String,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("dpop_bound_access_tokens") val dpopBoundAccessTokens: Boolean,
    @SerialName("dpop_require_nonce") val dpopRequireNonce: Boolean,
    @SerialName("grant_types") val grantTypes: List<String>,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("jwks") val jwks: String? = null,
    @SerialName("jwks_uri") val jwksUri: String? = null,
    @SerialName("name") val name: String,
    @SerialName("profile") val profile: ClientProfile,
    @SerialName("redirect_uris") val redirectUris: List<String>,
    @SerialName("require_par") val requirePar: Boolean,
    @SerialName("scopes") val scopes: List<String>,
    @SerialName("self_signed_tls_client_auth_thumbprints") val selfSignedTlsClientAuthThumbprints: List<String>,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("tls_client_auth_san_dns") val tlsClientAuthSanDns: String? = null,
    @SerialName("tls_client_auth_san_uri") val tlsClientAuthSanUri: String? = null,
    @SerialName("tls_client_auth_subject_dn") val tlsClientAuthSubjectDn: String? = null,
    @SerialName("tls_client_certificate_bound_access_tokens") val tlsClientCertificateBoundAccessTokens: Boolean,
    @SerialName("token_endpoint_auth_method") val tokenEndpointAuthMethod: ClientAuthMethod,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
