// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The OidcAuthorizeRequest schema from the server's OpenAPI document.
 *
 * @property configId ID of the federation config to use.
 * @property nonce Nonce for replay protection (generated by the caller).
 * @property redirectUri Redirect URI the external IdP should return the user to.
 * @property state CSRF state value (generated by the caller).
 */
@Serializable
data class OidcAuthorizeRequest(
    @SerialName("config_id") val configId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("nonce") val nonce: String,
    @SerialName("redirect_uri") val redirectUri: String,
    @SerialName("state") val state: String,
)
