// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The OidcCallbackRequest schema from the server's OpenAPI document.
 *
 * @property code Authorization code returned by the external IdP.
 * @property configId ID of the federation config used in the authorization request.
 * @property nonce Client-supplied nonce (SECHRD-07/D-04: retained for backward compatibility
 *     with older callers, but IGNORED for verification — `expected_nonce` always comes from the
 *     server-side `FederationLoginState` row looked up via `state`, never from this field).
 * @property redirectUri Redirect URI that was used in the authorization request.
 * @property state CSRF state value from the authorization request. Used to look up the
 *     server-side `FederationLoginState` row that holds the real nonce (SECHRD-07/D-04) — required
 *     so the callback can find its login state.
 */
@Serializable
data class OidcCallbackRequest(
    @SerialName("code") val code: String,
    @SerialName("config_id") val configId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("nonce") val nonce: String,
    @SerialName("redirect_uri") val redirectUri: String,
    @SerialName("state") val state: String,
)
