// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The client-supplied half of an OPAQUE enrolment, as it appears inside registration /
 * change-password / reset-completion / bootstrap request bodies. There is no standalone
 * `register/finish` endpoint, deliberately. A record can only be created at a moment when the
 * plaintext password legitimately exists on the client, and every one of those moments is already
 * an endpoint that takes a password. A free-standing finish would be an endpoint whose only job is
 * to attach a credential to an account, which is a thing worth not having. Kept separate from
 * &#91;`CreateOpaqueCredential`&#93; because the tenant, the user and the credential identifier
 * are all decided by the server — a client that could name them could enrol a record against
 * somebody else's account.
 *
 * @property opaqueSession The `opaque_session` from the register/start response, echoed
 *     verbatim.
 * @property registrationRecord Lowercase-hex serialized RFC 9807 `RegistrationRecord`.
 */
@Serializable
data class OpaqueEnrollment(
    @SerialName("opaque_session") val opaqueSession: String,
    @SerialName("registration_record") val registrationRecord: String,
)
