// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * An organization groups multiple tenants under a single administrative entity. Organizations
 * represent companies, departments, or business units. CA certificates are registered at the
 * organization level, enabling a hierarchical trust model across all tenants.
 *
 * @property createdAt the server's created_at field
 * @property id the server's id field
 * @property metadata Arbitrary key-value metadata.
 * @property name Human-readable name.
 * @property slug URL-safe unique identifier (e.g., `acme-corp`).
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class Organization(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("metadata") val metadata: JsonElement,
    @SerialName("name") val name: String,
    @SerialName("slug") val slug: String,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
