// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `POST …/saml/parse-sp-metadata` body: **exactly one** of the two members.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property metadataUrl An `https` URL the server fetches the document from, once, through its
 *     SSRF guard.
 * @property metadataXml A metadata document, at most 512 KiB.
 */
@Serializable
data class ParseSamlSpMetadata(
    @SerialName("metadata_url") val metadataUrl: String? = null,
    @SerialName("metadata_xml") val metadataXml: String? = null,
) {
    companion object {
        /**
         * A request for the server to fetch the SP's metadata from an https URL, through its SSRF
         * guard (§29.2).
         *
         * @param metadataUrl the value to send
         * @return a ParseSamlSpMetadata carrying only [metadataUrl]
         */
        fun fromUrl(metadataUrl: String): ParseSamlSpMetadata = ParseSamlSpMetadata(metadataUrl = metadataUrl)

        /**
         * A request carrying the SP's metadata document itself, at most 512 KiB (§29.2).
         *
         * @param metadataXml the value to send
         * @return a ParseSamlSpMetadata carrying only [metadataXml]
         */
        fun fromXml(metadataXml: String): ParseSamlSpMetadata = ParseSamlSpMetadata(metadataXml = metadataXml)
    }
}
