// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The Permission schema from the server's OpenAPI document.
 *
 * @property action The action this permission represents (e.g., `read`, `write`, `delete`).
 * @property createdAt the server's created_at field
 * @property description the server's description field
 * @property id the server's id field
 * @property tenantId the server's tenant_id field
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class Permission(
    @SerialName("action") val action: String,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("description") val description: String,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
