// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An OpenPGP key stored by AXIAM.
 *
 * @property algorithm the server's algorithm field
 * @property createdAt the server's created_at field
 * @property fingerprint OpenPGP key fingerprint (hex).
 * @property id the server's id field
 * @property name the server's name field
 * @property publicKeyArmored the server's public_key_armored field
 * @property purpose the server's purpose field
 * @property status the server's status field
 * @property tenantId the server's tenant_id field
 */
@Serializable
data class PgpKey(
    @SerialName("algorithm") val algorithm: PgpKeyAlgorithm,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("fingerprint") val fingerprint: String,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("name") val name: String,
    @SerialName("public_key_armored") val publicKeyArmored: String,
    @SerialName("purpose") val purpose: PgpKeyPurpose,
    @SerialName("status") val status: PgpKeyStatus,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
)
