// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `GET` response: the stored policy plus the unknown-AAGUID action it currently *resolves to*.
 * `unknown_aaguid` is nullable, where `null` means "use this mode's default" (deny under
 * `direct_required`, allow otherwise). A client that only saw the stored `null` would have to
 * re-derive that rule itself to display what the policy actually does — and a security rule
 * implemented twice is a security rule that will eventually disagree with itself. So the server
 * resolves it once, here, and reports both: the admin's stored intent and its effect.
 *
 * @property allowedAaguids `None` = every AAGUID is allowed except `blocked_aaguids`.
 *     `Some(vec!&#91;&#93;)` is a deliberate "nothing may register" policy and is accepted as
 *     such: `evaluate` denies every AAGUID against an empty allow-list. Nothing rejects it,
 *     precisely because the failure direction is safe — a client that sends `&#91;&#93;` when it
 *     meant `null` gets a locked-down tenant, which is visible immediately, rather than an open
 *     one, which is not.
 * @property blockRevokedStatus Deny registration if the MDS entry has ever reported `REVOKED`
 *     or any `*_COMPROMISE` status (sticky — D8 step 7).
 * @property blockedAaguids the server's blocked_aaguids field
 * @property effectiveUnknownAaguid The action actually applied to an AAGUID with no MDS
 *     metadata, with `unknown_aaguid: null` resolved against `mode`. Read-only — `PUT` ignores it.
 * @property minCertification the server's min_certification field
 * @property mode the server's mode field
 * @property requireFidoCertified Require *some* `FIDO_CERTIFIED*` status, any level.
 *     Independent of (and checked before) `min_certification`.
 * @property unknownAaguid the server's unknown_aaguid field
 */
@Serializable
data class PolicyResponse(
    @SerialName("allowed_aaguids") val allowedAaguids: List<@Serializable(with = UuidSerializer::class) UUID>? = null,
    @SerialName("block_revoked_status") val blockRevokedStatus: Boolean,
    @SerialName("blocked_aaguids") val blockedAaguids: List<@Serializable(with = UuidSerializer::class) UUID>? = null,
    @SerialName("effective_unknown_aaguid") val effectiveUnknownAaguid: UnknownAaguidAction,
    @SerialName("min_certification") val minCertification: CertificationLevel? = null,
    @SerialName("mode") val mode: AttestationMode,
    @SerialName("require_fido_certified") val requireFidoCertified: Boolean,
    @SerialName("unknown_aaguid") val unknownAaguid: UnknownAaguidAction? = null,
)
