// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The ReactorResponse schema from the server's OpenAPI document.
 *
 * @property createdAt the server's created_at field
 * @property description the server's description field
 * @property enabled the server's enabled field
 * @property events the server's events field
 * @property failurePolicy the server's failure_policy field
 * @property id the server's id field
 * @property lastSeenAt When this reactor last consumed from its queue. `null` means it has
 *     never connected — which the admin UI shows differently from "connected once, silent since".
 * @property mode the server's mode field
 * @property name the server's name field
 * @property priority the server's priority field
 * @property recentTimeoutCount R2.3: dispatch failures against this registration in the last
 *     24h whose cause was a timeout (as opposed to a rejected reply, a transport failure, or
 *     overload), capped at 100 — a health signal read from the audit trail R2.2 started writing,
 *     not a replacement for the audit log itself (`GET /api/v1/audit-log` is that).
 * @property recentVetoCount R2.3: operations this reactor's own reply *denied* in the last
 *     24h, capped at 100. Distinct from `recent_timeout_count`: a veto is the reactor working as
 *     designed; a timeout is the reactor not answering.
 * @property tenantId the server's tenant_id field
 * @property timeoutMs the server's timeout_ms field
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class ReactorResponse(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("description") val description: String,
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("events") val events: List<String>,
    @SerialName("failure_policy") val failurePolicy: FailurePolicy,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("last_seen_at") val lastSeenAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("mode") val mode: ReactorMode,
    @SerialName("name") val name: String,
    @SerialName("priority") val priority: Int,
    @SerialName("recent_timeout_count") val recentTimeoutCount: Int,
    @SerialName("recent_veto_count") val recentVetoCount: Int,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("timeout_ms") val timeoutMs: Int,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
