// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The ReadyResponse schema from the server's OpenAPI document.
 *
 * @property database the server's database field
 * @property status the server's status field
 */
@Serializable
data class ReadyResponse(
    @SerialName("database") val database: String,
    @SerialName("status") val status: String,
)
