// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Metadata only. The handle exists in plaintext exactly once, in
 * &#91;`CreateRegistrationTokenResponse`&#93;.
 *
 * @property createdAt Row creation time.
 * @property createdBy The administrator who minted it.
 * @property expiresAt When it stops being usable.
 * @property id Row identity.
 * @property name The operator-facing label.
 * @property tenantId The tenant a registration on this token lands in.
 * @property usedAt When it was spent, if it was.
 * @property usedByClientId Reserved; always absent in this build. See
 *     `axiam_core::models::oauth2_registration_token::OAuth2RegistrationToken::used_by_client_id`
 *     — the registration a token produced is recorded in the audit log, not here.
 */
@Serializable
data class RegistrationTokenResponse(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("created_by") val createdBy: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("expires_at") val expiresAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("name") val name: String,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("used_at") val usedAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("used_by_client_id") val usedByClientId: String? = null,
)
