// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A permission grant with its scopes resolved. A superset of &#91;`PermissionGrant`&#93;:
 * `scope_ids` is still present and still authoritative, so a client written before `scopes`
 * existed is unaffected.
 *
 * @property effect Whether the grant permits or refuses.
 * @property permission The permission this grant is about.
 * @property scopeIds The scope ids the grant is constrained to. Empty is the wildcard.
 * @property scopes The scopes `scope_ids` names, in the same order where resolvable. A scope
 *     that cannot be resolved is **omitted** rather than represented by a placeholder, so this can
 *     be shorter than `scope_ids`. That happens when a scope was deleted while a grant still
 *     referenced it, and showing a name for something that no longer exists would be worse than
 *     showing one fewer chip beside a count that still says how many ids the grant carries.
 */
@Serializable
data class ResolvedPermissionGrant(
    @SerialName("effect") val effect: PermissionEffect,
    @SerialName("permission") val permission: Permission,
    @SerialName("scope_ids") val scopeIds: List<@Serializable(with = UuidSerializer::class) UUID>,
    @SerialName("scopes") val scopes: List<GrantedScope>,
)
