// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A group together with the resource scope of its assignment of this role.
 *
 * @property group The assigned group.
 * @property resourceId `None` means the role was assigned globally (no resource scope).
 */
@Serializable
data class RoleGroupAssignment(
    @SerialName("group") val group: Group,
    @SerialName("resource_id") val resourceId: @Serializable(with = UuidSerializer::class) UUID? = null,
)
