// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A role together with its assignment context (the resource it is scoped to).
 *
 * @property resourceId `None` means the role was assigned globally (no resource scope).
 * @property role the server's role field
 */
@Serializable
data class RoleAssignment(
    @SerialName("resource_id") val resourceId: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("role") val role: Role,
)
