// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response for secret rotation.
 *
 * @property clientSecret the server's client_secret field -- SECRET: redacted from toString
 *     and from every rendering except the one request body it is sent in
 */
@Serializable
data class RotateSecretResponse(
    @SerialName("client_secret") val clientSecret: @Contextual Sensitive<String>,
)
