// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The tenant's SAML IdP, as the administrator needs to see it before and while switching it on:
 * what an SP will be given, and whether it answers yet.
 *
 * @property activeCredentialId The `active` credential, or null.
 * @property entityId The IdP's entity id (the metadata URL itself).
 * @property metadataServed Whether `metadata_url` answers now: SAML is available, enabled for
 *     the tenant, and an `active` or `next` credential exists (D-40).
 * @property metadataUrl Where the IdP metadata is served.
 * @property nextCredentialId The `next` credential, or null.
 * @property samlAvailable Whether this server build serves SAML at all (it was built with the
 *     `saml` feature).
 * @property samlIdpEnabled The tenant's **effective** `saml_idp_enabled` setting (D-20).
 *     Written through the `settings` operations, not here.
 * @property sloUrl The single-logout endpoint.
 * @property ssoUrl The single-sign-on endpoint.
 * @property tenantId The tenant.
 */
@Serializable
data class SamlIdpInfo(
    @SerialName("active_credential_id") val activeCredentialId: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("entity_id") val entityId: String,
    @SerialName("metadata_served") val metadataServed: Boolean,
    @SerialName("metadata_url") val metadataUrl: String,
    @SerialName("next_credential_id") val nextCredentialId: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("saml_available") val samlAvailable: Boolean,
    @SerialName("saml_idp_enabled") val samlIdpEnabled: Boolean,
    @SerialName("slo_url") val sloUrl: String,
    @SerialName("sso_url") val ssoUrl: String,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
)
