// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * What promoting the `next` credential did.
 *
 * @property active The credential that is now `active`.
 * @property retired the server's retired field
 */
@Serializable
data class SamlIdpCredentialPromotion(
    @SerialName("active") val active: SamlIdpCredential,
    @SerialName("retired") val retired: SamlIdpCredential? = null,
)
