// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.put

/**
 * Everything an administrator supplies when registering or replacing a service provider (`create`
 * and `update` both take it; `update` is a full replacement). Every field but `entity_id`,
 * `display_name` and `acs_urls` has a default, so a client written against a later revision of
 * this struct keeps working.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property acsUrls The ACS allow-list. At least one, at most one default.
 * @property allowIdpInitiated Whether IdP-initiated SSO is allowed for this SP (D-3). A per-SP
 *     opt-in, off by default: an unsolicited assertion has no `InResponseTo` to bind it to a
 *     request the SP made.
 * @property allowedGroups Groups whose members may sign in to this SP. **Empty means every
 *     active user of the tenant may.** Evaluated by the SSO endpoint (T23.2.3).
 * @property attributeMappings Attribute mapping table, at most
 *     &#91;`MAX_ATTRIBUTE_MAPPINGS`&#93; entries.
 * @property displayName Human-readable name for the console.
 * @property enabled Whether the SP may sign in at all. A disabled SP stays registered but
 *     every SSO request for it is refused.
 * @property encryptAssertions Encrypt assertions to the SP's encryption certificate (D-2). Off
 *     by default; requires &#91;`Self::sp_encryption_cert_pem`&#93;.
 * @property entityId The SP's `entityID`, unique per tenant. At most
 *     &#91;`MAX_ENTITY_ID_BYTES`&#93;.
 * @property nameIdFormat `NameID` policy. Default: persistent, pairwise.
 * @property signResponses Sign the `<samlp:Response>` envelope as well as the assertion (which
 *     is signed always). Default **`true`**: it costs nothing and many SPs require it.
 * @property sloBinding the server's slo_binding field
 * @property sloUrl Single-logout endpoint, if the SP supports it.
 * @property spEncryptionCertPem PEM certificate assertions are encrypted to. Required when
 *     `encrypt_assertions` is set.
 * @property spSigningCertPem PEM certificate the SP signs its `AuthnRequest`s with.
 * @property wantAuthnRequestsSigned Refuse an `AuthnRequest` that is not signed by
 *     `sp_signing_cert_pem`. Requires that certificate.
 */
@Serializable
data class SamlServiceProviderInput(
    @SerialName("acs_urls") val acsUrls: List<AcsEndpoint>,
    @SerialName("allow_idp_initiated") val allowIdpInitiated: Boolean? = null,
    @SerialName("allowed_groups") val allowedGroups: List<@Serializable(with = UuidSerializer::class) UUID>? = null,
    @SerialName("attribute_mappings") val attributeMappings: List<AttributeMapping>? = null,
    @SerialName("display_name") val displayName: String,
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("encrypt_assertions") val encryptAssertions: Boolean? = null,
    @SerialName("entity_id") val entityId: String,
    @SerialName("name_id_format") val nameIdFormat: NameIdFormat? = null,
    @SerialName("sign_responses") val signResponses: Boolean? = null,
    @SerialName("slo_binding") val sloBinding: SamlBinding? = null,
    @SerialName("slo_url") val sloUrl: String? = null,
    @SerialName("sp_encryption_cert_pem") val spEncryptionCertPem: String? = null,
    @SerialName("sp_signing_cert_pem") val spSigningCertPem: String? = null,
    @SerialName("want_authn_requests_signed") val wantAuthnRequestsSigned: Boolean? = null,
)
