// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A parse of SP metadata: **a draft, not a registration**. Nothing is stored until the caller
 * submits `service_provider` to `create_service_provider` or `update_service_provider`, and
 * nothing in it is trusted because it came from a document (D-41).
 *
 * @property encryptionCertificateFingerprint Lower-case hex SHA-256 of the encryption
 *     certificate's DER the draft carries, or null.
 * @property serviceProvider A body `create_service_provider` accepts unchanged (bar the rules
 *     that need the datastore). `encrypt_assertions` is never set.
 * @property signingCertificateFingerprint Lower-case hex SHA-256 of the signing certificate's
 *     DER the draft carries, or null.
 * @property warnings What to know before submitting it. Human text; do not parse it.
 */
@Serializable
data class SamlSpMetadataDraft(
    @SerialName("encryption_certificate_fingerprint") val encryptionCertificateFingerprint: String? = null,
    @SerialName("service_provider") val serviceProvider: SamlServiceProviderInput,
    @SerialName("signing_certificate_fingerprint") val signingCertificateFingerprint: String? = null,
    @SerialName("warnings") val warnings: List<String>,
)
