// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The body of a started reconciliation's `202`.
 *
 * @property status Always `started`.
 * @property targetId The target being reconciled.
 */
@Serializable
data class ScimReconcileAccepted(
    @SerialName("status") val status: String,
    @SerialName("target_id") val targetId: @Serializable(with = UuidSerializer::class) UUID,
)
