// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import io.axiam.sdk.management.InstantSerializer
import java.time.Instant
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.put

/**
 * `create` and `update` (a **replacement**) body.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property auth `bearer`, or `oauth2_client_credentials` with `token_url` (the same URL
 *     policy), `client_id` (1–256 bytes) and an optional `scope`.
 * @property baseUrl The downstream's SCIM service root: an `https` URL under the outbound
 *     address policy (no credentials or fragment, at most 2 048 bytes, no non-public address, no
 *     local name).
 * @property credential **Write-only.** The bearer token or the OAuth2 client secret, 1–4 096
 *     bytes. Required on create. On update, absent keeps the stored one — except that moving it to
 *     another URL (`base_url` of a bearer target, `token_url` or `base_url` of a
 *     client-credentials one) or switching `auth.type` requires it again. -- SECRET: redacted from
 *     toString and from every rendering except the one request body it is sent in
 * @property deprovision `deactivate` (default: `PATCH active=false`) or `delete`.
 * @property enabled `true` by default. A disabled target receives nothing.
 * @property expectedUpdatedAt The `updated_at` of the target as the client read it (P23W5-09,
 *     T-416). **Update only; create ignores it.** When present, the replacement lands only if the
 *     target still has that version, else `409` (reload and retry): two administrators who opened
 *     the form at the same version cannot silently overwrite each other. When absent the
 *     replacement is conditional on the version the server reads during the request —
 *     last-writer-wins between administrators, as before.
 * @property name 1–128 bytes.
 * @property pushGroups Push groups too (every group for `all_users`, the listed ones for
 *     `groups`). `false` by default.
 * @property scope `all_users`, or `groups` with 1–100 `group_ids` of this tenant: users who
 *     are direct members of any listed group.
 * @property userNameFrom `username` (default) or `email`.
 */
@Serializable
data class ScimTargetInput(
    @SerialName("auth") val auth: ScimTargetAuth,
    @SerialName("base_url") val baseUrl: String,
    @SerialName("credential") val credential: @Contextual Sensitive<String>? = null,
    @SerialName("deprovision") val deprovision: DeprovisionPolicy? = null,
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("expected_updated_at") val expectedUpdatedAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("name") val name: String,
    @SerialName("push_groups") val pushGroups: Boolean? = null,
    @SerialName("scope") val scope: ScimTargetScope,
    @SerialName("user_name_from") val userNameFrom: UserNameSource? = null,
)
