// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.jsonObject

/**
 * How AXIAM authenticates to the downstream service provider, without the credential itself.
 *
 * Shapes discriminated by the type field. The set is OPEN (CONTRACT §31.2): a type this SDK does
 * not know decodes as [ScimTargetAuth.Unknown] rather than failing the response it arrived in, and
 * that arm is never sent -- encoding it fails locally, before any request. Sealed, so a `when`
 * over the arms is still exhaustive: the unknown arm is one of them.
 */
@Serializable(with = ScimTargetAuth.Companion.Serializer::class)
sealed interface ScimTargetAuth {

    /**
     * A type this SDK does not know -- reachable only by decoding.
     *
     * Only the type itself is kept; the members it arrived with are dropped, which is also why it
     * cannot be sent (CONTRACT §31.2). Read the record, and if this is the arm, supply a known one
     * in the write instead.
     *
     * @property type the type value the server sent
     */
    data class Unknown(val type: String) : ScimTargetAuth

    companion object {
        /**
         * Dispatches on the tag by hand: an unknown tag decodes to [Unknown]
         * instead of throwing, and [Unknown] refuses to encode (§31.2).
         */
        internal object Serializer : KSerializer<ScimTargetAuth> {
            override val descriptor: SerialDescriptor =
                buildClassSerialDescriptor("io.axiam.sdk.management.models.ScimTargetAuth")

            override fun serialize(encoder: Encoder, value: ScimTargetAuth) {
                val output = encoder as? JsonEncoder
                    ?: error("ScimTargetAuth can only be serialized as JSON")
                val (tag, members) = when (value) {
                    is ScimTargetAuthBearer -> "bearer" to
                        output.json.encodeToJsonElement(ScimTargetAuthBearer.serializer(), value)
                    is ScimTargetAuthOauth2ClientCredentials -> "oauth2_client_credentials" to
                        output.json.encodeToJsonElement(ScimTargetAuthOauth2ClientCredentials.serializer(), value)
                    is Unknown -> throw SerializationException(
                        "ScimTargetAuth type \"${value.type}\" is not one this SDK " +
                            "knows, so it is never sent (CONTRACT §31.2)",
                    )
                }
                output.encodeJsonElement(
                    kotlinx.serialization.json.JsonObject(
                        mapOf("type" to kotlinx.serialization.json.JsonPrimitive(tag)) +
                            members.jsonObject,
                    ),
                )
            }

            override fun deserialize(decoder: Decoder): ScimTargetAuth {
                val input = decoder as? JsonDecoder
                    ?: error("ScimTargetAuth can only be deserialized from JSON")
                val obj = input.decodeJsonElement().jsonObject
                val tag = (obj["type"] as? kotlinx.serialization.json.JsonPrimitive)
                    ?.takeIf { it.isString }?.content
                val members = kotlinx.serialization.json.JsonObject(obj - "type")
                return when (tag) {
                    "bearer" -> input.json.decodeFromJsonElement(ScimTargetAuthBearer.serializer(), members)
                    "oauth2_client_credentials" -> input.json.decodeFromJsonElement(ScimTargetAuthOauth2ClientCredentials.serializer(), members)
                    else -> Unknown(tag ?: "")
                }
            }
        }
    }
}
