// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The 'oauth2_client_credentials' arm of ScimTargetAuth.
 *
 * @property clientId The OAuth2 client id.
 * @property scope The scope requested, if any.
 * @property tokenUrl The token endpoint the client secret is sent to.
 */
@Serializable
@SerialName("oauth2_client_credentials")
data class ScimTargetAuthOauth2ClientCredentials(
    @SerialName("client_id") val clientId: String,
    @SerialName("scope") val scope: String? = null,
    @SerialName("token_url") val tokenUrl: String,
) : ScimTargetAuth
