// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.jsonObject

/**
 * Which users a target provisions.
 *
 * Shapes discriminated by the type field. The set is OPEN (CONTRACT §31.2): a type this SDK does
 * not know decodes as [ScimTargetScope.Unknown] rather than failing the response it arrived in,
 * and that arm is never sent -- encoding it fails locally, before any request. Sealed, so a `when`
 * over the arms is still exhaustive: the unknown arm is one of them.
 */
@Serializable(with = ScimTargetScope.Companion.Serializer::class)
sealed interface ScimTargetScope {

    /**
     * A type this SDK does not know -- reachable only by decoding.
     *
     * Only the type itself is kept; the members it arrived with are dropped, which is also why it
     * cannot be sent (CONTRACT §31.2). Read the record, and if this is the arm, supply a known one
     * in the write instead.
     *
     * @property type the type value the server sent
     */
    data class Unknown(val type: String) : ScimTargetScope

    companion object {
        /**
         * Dispatches on the tag by hand: an unknown tag decodes to [Unknown]
         * instead of throwing, and [Unknown] refuses to encode (§31.2).
         */
        internal object Serializer : KSerializer<ScimTargetScope> {
            override val descriptor: SerialDescriptor =
                buildClassSerialDescriptor("io.axiam.sdk.management.models.ScimTargetScope")

            override fun serialize(encoder: Encoder, value: ScimTargetScope) {
                val output = encoder as? JsonEncoder
                    ?: error("ScimTargetScope can only be serialized as JSON")
                val (tag, members) = when (value) {
                    is ScimTargetScopeAllUsers -> "all_users" to
                        output.json.encodeToJsonElement(ScimTargetScopeAllUsers.serializer(), value)
                    is ScimTargetScopeGroups -> "groups" to
                        output.json.encodeToJsonElement(ScimTargetScopeGroups.serializer(), value)
                    is Unknown -> throw SerializationException(
                        "ScimTargetScope type \"${value.type}\" is not one this SDK " +
                            "knows, so it is never sent (CONTRACT §31.2)",
                    )
                }
                output.encodeJsonElement(
                    kotlinx.serialization.json.JsonObject(
                        mapOf("type" to kotlinx.serialization.json.JsonPrimitive(tag)) +
                            members.jsonObject,
                    ),
                )
            }

            override fun deserialize(decoder: Decoder): ScimTargetScope {
                val input = decoder as? JsonDecoder
                    ?: error("ScimTargetScope can only be deserialized from JSON")
                val obj = input.decodeJsonElement().jsonObject
                val tag = (obj["type"] as? kotlinx.serialization.json.JsonPrimitive)
                    ?.takeIf { it.isString }?.content
                val members = kotlinx.serialization.json.JsonObject(obj - "type")
                return when (tag) {
                    "all_users" -> input.json.decodeFromJsonElement(ScimTargetScopeAllUsers.serializer(), members)
                    "groups" -> input.json.decodeFromJsonElement(ScimTargetScopeGroups.serializer(), members)
                    else -> Unknown(tag ?: "")
                }
            }
        }
    }
}
