// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A registered SCIM target, as the management API returns it. **The credential is never
 * returned**, and there is no member that says anything about it.
 *
 * @property auth How AXIAM authenticates to it (no credential).
 * @property baseUrl The downstream's SCIM service root.
 * @property createdAt When the target was registered.
 * @property deprovision What happens downstream to a user who leaves scope or is no longer
 *     active (erasure always deletes).
 * @property enabled Whether AXIAM pushes to it.
 * @property id The target id.
 * @property name The name.
 * @property pushGroups Whether groups are pushed too.
 * @property scope Which users it provisions.
 * @property state the server's state field
 * @property tenantId The owning tenant.
 * @property updatedAt When it was last written: the version an update is conditional on.
 * @property userNameFrom Which attribute becomes `userName`.
 */
@Serializable
data class ScimTargetResponse(
    @SerialName("auth") val auth: ScimTargetAuth,
    @SerialName("base_url") val baseUrl: String,
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("deprovision") val deprovision: DeprovisionPolicy,
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("name") val name: String,
    @SerialName("push_groups") val pushGroups: Boolean,
    @SerialName("scope") val scope: ScimTargetScope,
    @SerialName("state") val state: ScimTargetDeliveryState? = null,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("user_name_from") val userNameFrom: UserNameSource,
)
