// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The 'all_users' arm of ScimTargetScope.
 */
@Serializable
@SerialName("all_users")
class ScimTargetScopeAllUsers : ScimTargetScope
