// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import java.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A target's delivery state, as `GET` projects it. Fixed vocabulary only: the failure reason is
 * one of the deliverer's phrases, never a URL, a response body or a value.
 *
 * @property consecutiveFailures Failed attempts since the last success.
 * @property deadLetteredTotal Deliveries dead-lettered over the target's lifetime.
 * @property lastFailureAt When a delivery attempt last failed or was dead-lettered.
 * @property lastFailureReason Why, in the deliverer's fixed vocabulary.
 * @property lastReconciledAt When reconciliation last ran.
 * @property lastSuccessAt When a delivery last succeeded.
 */
@Serializable
data class ScimTargetDeliveryState(
    @SerialName("consecutive_failures") val consecutiveFailures: Long,
    @SerialName("dead_lettered_total") val deadLetteredTotal: Long,
    @SerialName("last_failure_at") val lastFailureAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("last_failure_reason") val lastFailureReason: String? = null,
    @SerialName("last_reconciled_at") val lastReconciledAt: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("last_success_at") val lastSuccessAt: @Serializable(with = InstantSerializer::class) Instant? = null,
)
