// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The 'groups' arm of ScimTargetScope.
 *
 * @property groupIds Users who are direct members of any listed group.
 */
@Serializable
@SerialName("groups")
data class ScimTargetScopeGroups(
    @SerialName("group_ids") val groupIds: List<@Serializable(with = UuidSerializer::class) UUID>,
) : ScimTargetScope
