// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * One of a user's sessions, as an administrator sees it.
 *
 * @property amr RFC 8176 method references for that authentication.
 * @property authenticatedAt X7.2 — when the end user actually authenticated, which is not
 *     `created_at` on a session produced by refresh rotation.
 * @property createdAt the server's created_at field
 * @property expiresAt the server's expires_at field
 * @property id the server's id field
 * @property ipAddress the server's ip_address field
 * @property refreshReplayAt T-254 — when a refresh token of this session was last presented
 *     after it had already been rotated. `None` if that has never happened.
 * @property refreshReplayGraceAccepted T-254 — replays accepted under the FAPI 2.0 §5.3.2.1-9
 *     grace window. Only ever non-zero for a client registered `profile: fapi2`.
 * @property refreshReplayRefused T-254 — replays refused because there was no window to accept
 *     them in. Nothing a conformant client does.
 * @property refreshReplayVerdict T-254 — the badge: `none`, `fapi_grace_retry` or `refused`.
 *     Derived from the two counters below rather than stored, so it cannot disagree with them. A
 *     refusal outranks an accepted grace retry however the counts compare.
 * @property userAgent the server's user_agent field
 */
@Serializable
data class SessionResponse(
    @SerialName("amr") val amr: List<String>,
    @SerialName("authenticated_at") val authenticatedAt: String,
    @SerialName("created_at") val createdAt: String,
    @SerialName("expires_at") val expiresAt: String,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("ip_address") val ipAddress: String? = null,
    @SerialName("refresh_replay_at") val refreshReplayAt: String? = null,
    @SerialName("refresh_replay_grace_accepted") val refreshReplayGraceAccepted: Int,
    @SerialName("refresh_replay_refused") val refreshReplayRefused: Int,
    @SerialName("refresh_replay_verdict") val refreshReplayVerdict: String,
    @SerialName("user_agent") val userAgent: String? = null,
)
