// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `PUT /api/v1/tenants/{tenant_id}/directory` — a **replacement**. Every `DirectoryConfig` member
 * except `id`, `tenant_id` and the two timestamps, plus the write-only `bind_secret`. An omitted
 * optional member is **reset to its default**, not kept.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property baseDn Where users are searched for.
 * @property bindDn The service account the search runs as.
 * @property bindSecret The service account's password: **write-only**, 1 to 4096 octets.
 *     Required when the tenant has no configuration yet; on a replacement, absent means *keep the
 *     stored secret* — unless the write moves the connection (`url`, `start_tls`, `bind_dn` or
 *     `trust_anchors_pem`), which then requires it (`400`, P23W2-01). -- SECRET: redacted from
 *     toString and from every rendering except the one request body it is sent in
 * @property enabled A disabled directory serves no sign-in and is not synced.
 * @property groupBaseDn Defaults to null.
 * @property groupFilter Defaults to null.
 * @property groupMappings At most 500; every `group_id` a group of the tenant. Default empty.
 * @property groupMemberAttribute Defaults by `kind`.
 * @property groupNestingDepth `0..=10`, default 5.
 * @property jitProvisioning Default false.
 * @property kind Chooses defaults only.
 * @property startTls Upgrade an `ldap://` connection with StartTLS before any bind.
 * @property syncIntervalSecs `300..=86400`, default 3600.
 * @property trustAnchorsPem At most 16 CA certificates in PEM. Default empty (the public
 *     roots).
 * @property url `ldaps://host&#91;:port&#93;`, or `ldap://host&#91;:port&#93;` with
 *     `start_tls`.
 * @property userAttributeMap the server's user_attribute_map field
 * @property userFilter One `{username}` placeholder in value position.
 */
@Serializable
data class SetDirectoryConfig(
    @SerialName("base_dn") val baseDn: String,
    @SerialName("bind_dn") val bindDn: String,
    @SerialName("bind_secret") val bindSecret: @Contextual Sensitive<String>? = null,
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("group_base_dn") val groupBaseDn: String? = null,
    @SerialName("group_filter") val groupFilter: String? = null,
    @SerialName("group_mappings") val groupMappings: List<GroupMapping>? = null,
    @SerialName("group_member_attribute") val groupMemberAttribute: String? = null,
    @SerialName("group_nesting_depth") val groupNestingDepth: Int? = null,
    @SerialName("jit_provisioning") val jitProvisioning: Boolean? = null,
    @SerialName("kind") val kind: DirectoryKind,
    @SerialName("start_tls") val startTls: Boolean,
    @SerialName("sync_interval_secs") val syncIntervalSecs: Long? = null,
    @SerialName("trust_anchors_pem") val trustAnchorsPem: List<String>? = null,
    @SerialName("url") val url: String,
    @SerialName("user_attribute_map") val userAttributeMap: UserAttributeMap? = null,
    @SerialName("user_filter") val userFilter: String,
)
