// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Body for `PUT .../ca-certificates/{id}/mtls-trust-anchor`.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property enabled Whether this CA should be trusted for client-certificate authentication.
 */
@Serializable
data class SetMtlsTrustAnchor(
    @SerialName("enabled") val enabled: Boolean,
)
