// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Input for setting organization-level email config.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property enabled the server's enabled field
 * @property fromEmail the server's from_email field
 * @property fromName the server's from_name field
 * @property provider the server's provider field
 * @property replyTo the server's reply_to field
 */
@Serializable
data class SetOrgEmailConfig(
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("from_email") val fromEmail: String,
    @SerialName("from_name") val fromName: String,
    @SerialName("provider") val provider: ProviderConfig,
    @SerialName("reply_to") val replyTo: String? = null,
)
