// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Input for setting organization-level security settings.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property accessTokenLifetimeSecs the server's access_token_lifetime_secs field
 * @property adminNotificationsEnabled the server's admin_notifications_enabled field
 * @property defaultCertValidityDays the server's default_cert_validity_days field
 * @property deletionGracePeriodDays the server's deletion_grace_period_days field
 * @property emailVerificationGracePeriodHours the server's
 *     email_verification_grace_period_hours field
 * @property emailVerificationRequired the server's email_verification_required field
 * @property hibpCheckEnabled the server's hibp_check_enabled field
 * @property lockoutBackoffMultiplier the server's lockout_backoff_multiplier field
 * @property lockoutDurationSecs the server's lockout_duration_secs field
 * @property maxCertValidityDays the server's max_cert_validity_days field
 * @property maxFailedLoginAttempts the server's max_failed_login_attempts field
 * @property maxLockoutDurationSecs the server's max_lockout_duration_secs field
 * @property mfaChallengeLifetimeSecs the server's mfa_challenge_lifetime_secs field
 * @property mfaEnforced the server's mfa_enforced field
 * @property minLength the server's min_length field
 * @property opaqueKsf the server's opaque_ksf field
 * @property opaqueMode the server's opaque_mode field
 * @property opaqueSuite the server's opaque_suite field
 * @property passwordHistoryCount the server's password_history_count field
 * @property refreshTokenLifetimeSecs the server's refresh_token_lifetime_secs field
 * @property requireDigits the server's require_digits field
 * @property requireLowercase the server's require_lowercase field
 * @property requireSymbols the server's require_symbols field
 * @property requireUppercase the server's require_uppercase field
 */
@Serializable
data class SetOrgSettings(
    @SerialName("access_token_lifetime_secs") val accessTokenLifetimeSecs: Long,
    @SerialName("admin_notifications_enabled") val adminNotificationsEnabled: Boolean,
    @SerialName("default_cert_validity_days") val defaultCertValidityDays: Int,
    @SerialName("deletion_grace_period_days") val deletionGracePeriodDays: Int? = null,
    @SerialName("email_verification_grace_period_hours") val emailVerificationGracePeriodHours: Int,
    @SerialName("email_verification_required") val emailVerificationRequired: Boolean,
    @SerialName("hibp_check_enabled") val hibpCheckEnabled: Boolean,
    @SerialName("lockout_backoff_multiplier") val lockoutBackoffMultiplier: Double,
    @SerialName("lockout_duration_secs") val lockoutDurationSecs: Long,
    @SerialName("max_cert_validity_days") val maxCertValidityDays: Int,
    @SerialName("max_failed_login_attempts") val maxFailedLoginAttempts: Int,
    @SerialName("max_lockout_duration_secs") val maxLockoutDurationSecs: Long,
    @SerialName("mfa_challenge_lifetime_secs") val mfaChallengeLifetimeSecs: Long,
    @SerialName("mfa_enforced") val mfaEnforced: Boolean,
    @SerialName("min_length") val minLength: Int,
    @SerialName("opaque_ksf") val opaqueKsf: String? = null,
    @SerialName("opaque_mode") val opaqueMode: String? = null,
    @SerialName("opaque_suite") val opaqueSuite: String? = null,
    @SerialName("password_history_count") val passwordHistoryCount: Int,
    @SerialName("refresh_token_lifetime_secs") val refreshTokenLifetimeSecs: Long,
    @SerialName("require_digits") val requireDigits: Boolean,
    @SerialName("require_lowercase") val requireLowercase: Boolean,
    @SerialName("require_symbols") val requireSymbols: Boolean,
    @SerialName("require_uppercase") val requireUppercase: Boolean,
)
