// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request body for signing an audit batch.
 *
 * @property entryIds the server's entry_ids field
 */
@Serializable
data class SignAuditBatchRequest(
    @SerialName("entry_ids") val entryIds: List<@Serializable(with = UuidSerializer::class) UUID>,
)
