// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Body of `POST .../tenants/{tenant_id}/signing-cas/sign-csr`. Deliberately carries no key
 * algorithm: it is the CSR's, read out of the request, because a caller who could state it
 * separately could state one the key does not have.
 *
 * @property csrPem PEM-encoded PKCS#10 certificate signing request.
 * @property parentCaId The organization CA that signs it.
 * @property validityDays Validity duration in days, capped to the parent's own expiry.
 */
@Serializable
data class SignIntermediateCsrRequest(
    @SerialName("csr_pem") val csrPem: String,
    @SerialName("parent_ca_id") val parentCaId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("validity_days") val validityDays: Int,
)
