// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A signed batch of audit log entries.
 *
 * @property batchId the server's batch_id field
 * @property entryIds the server's entry_ids field
 * @property signatureArmored ASCII-armored PGP signed message containing the audit batch
 *     payload.
 * @property signedAt the server's signed_at field
 * @property signingKeyId the server's signing_key_id field
 * @property tenantId the server's tenant_id field
 */
@Serializable
data class SignedAuditBatch(
    @SerialName("batch_id") val batchId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("entry_ids") val entryIds: List<@Serializable(with = UuidSerializer::class) UUID>,
    @SerialName("signature_armored") val signatureArmored: String,
    @SerialName("signed_at") val signedAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("signing_key_id") val signingKeyId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
)
