// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * SMTP-specific configuration. `password` is write-only (D-01):
 * `#&#91;serde(skip_serializing)&#93;` means it is never emitted in a GET/serialized response. On
 * the write path (D-02), `#&#91;serde(default)&#93;` lets a caller omit the field entirely
 * (deserializing to `""`); an empty string is the sentinel for "no new secret supplied — preserve
 * whatever is already stored" (see `SurrealEmailConfigRepository:: set_org_config`). A non-empty
 * value is a real secret to encrypt+replace.
 *
 * @property host the server's host field
 * @property port the server's port field
 * @property starttls Use STARTTLS (true) or implicit TLS (false).
 * @property username the server's username field
 */
@Serializable
data class SmtpConfig(
    @SerialName("host") val host: String,
    @SerialName("port") val port: Int,
    @SerialName("starttls") val starttls: Boolean,
    @SerialName("username") val username: String,
)
