// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * The six event types AXIAM transmits (G-5). Stored and sent as their event-type URIs;
 * &#91;`Self::ALL`&#93; is the canonical order every list AXIAM returns is sorted in.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [SsfEventType.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11 rule 1).
 * Its own wire spelling is the empty string, which no server value is: carrying an unrecognised
 * value back into an update is refused by the server rather than silently written as a spelling it
 * never used. A `when` over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = SsfEventType.Companion.Serializer::class)
enum class SsfEventType(val wire: String) {
    SESSION_REVOKED("https://schemas.openid.net/secevent/caep/event-type/session-revoked"),

    CREDENTIAL_CHANGE("https://schemas.openid.net/secevent/caep/event-type/credential-change"),

    ASSURANCE_LEVEL_CHANGE("https://schemas.openid.net/secevent/caep/event-type/assurance-level-change"),

    ACCOUNT_DISABLED("https://schemas.openid.net/secevent/risc/event-type/account-disabled"),

    ACCOUNT_ENABLED("https://schemas.openid.net/secevent/risc/event-type/account-enabled"),

    ACCOUNT_PURGED("https://schemas.openid.net/secevent/risc/event-type/account-purged"),

    /** A value this SDK's copy of the spec does not list; see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing.
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<SsfEventType> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.SsfEventType", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: SsfEventType) {
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): SsfEventType {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
