// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.put

/**
 * `create_stream` and `update_stream` (a **replacement**) body.
 *
 * This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a prior
 * read is not preserved, it is overwritten. Every property is required and none defaults, so
 * forgetting one is a compile error rather than a silent null on the wire. Read first, copy(),
 * write back.
 *
 * @property audience 1–512 bytes; unique across the deployment.
 * @property authorizationHeader **Write-only.** The `Authorization` header value AXIAM sends
 *     to a push endpoint. On update, absent keeps the stored one — except that moving the endpoint
 *     to another origin requires it again. -- SECRET: redacted from toString and from every
 *     rendering except the one request body it is sent in
 * @property clearAuthorizationHeader On update: remove the stored header. Refused together
 *     with `authorization_header`.
 * @property deliveryMethod `push` or `poll`.
 * @property description At most 256 bytes.
 * @property endpointUrl Required for `push` (an `https` URL under the outbound address
 *     policy), refused for `poll`.
 * @property eventsAllowed 1–6 event types.
 * @property eventsRequested A subset of `events_allowed`; absent means all of them. The
 *     receiver may narrow it later, never widen it.
 * @property receiverClientId An OAuth2 client of the tenant with the `client_credentials`
 *     grant and the `ssf.manage` scope.
 * @property status `enabled` by default.
 * @property statusReason At most 256 bytes.
 * @property subjectFormat `iss_sub` by default.
 */
@Serializable
data class SsfStreamInput(
    @SerialName("audience") val audience: String,
    @SerialName("authorization_header") val authorizationHeader: @Contextual Sensitive<String>? = null,
    @SerialName("clear_authorization_header") val clearAuthorizationHeader: Boolean? = null,
    @SerialName("delivery_method") val deliveryMethod: SsfDeliveryMethod,
    @SerialName("description") val description: String? = null,
    @SerialName("endpoint_url") val endpointUrl: String? = null,
    @SerialName("events_allowed") val eventsAllowed: List<SsfEventType>,
    @SerialName("events_requested") val eventsRequested: List<SsfEventType>? = null,
    @SerialName("receiver_client_id") val receiverClientId: String,
    @SerialName("status") val status: SsfStreamStatus? = null,
    @SerialName("status_reason") val statusReason: String? = null,
    @SerialName("subject_format") val subjectFormat: SsfSubjectFormat? = null,
)
