// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A tenant is an isolated context within an organization. Each tenant has its own set of users,
 * roles, permissions, resources, certificates, and configuration. Tenants can represent
 * environments (dev/staging/prod) or separate business contexts.
 *
 * @property createdAt the server's created_at field
 * @property id the server's id field
 * @property kind Whether this is an ordinary tenant or the organization's own scope.
 *     `#&#91;serde(default)&#93;` so every row written before organization scope existed reads
 *     back as &#91;`TenantKind::Standard`&#93;, which is what it is.
 * @property metadata Arbitrary key-value metadata.
 * @property name Human-readable name.
 * @property organizationId The organization this tenant belongs to.
 * @property slug URL-safe unique identifier within the organization (e.g., `production`).
 * @property status Lifecycle status. New tenants default to &#91;`TenantStatus::Active`&#93;.
 * @property updatedAt the server's updated_at field
 */
@Serializable
data class Tenant(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("kind") val kind: TenantKind? = null,
    @SerialName("metadata") val metadata: JsonElement,
    @SerialName("name") val name: String,
    @SerialName("organization_id") val organizationId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("slug") val slug: String,
    @SerialName("status") val status: TenantStatus,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
)
