// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * What a tenant *is*, as distinct from what state it is in. Reserved rather than inferred: an
 * organization has exactly one tenant of kind &#91;`Self::Organization`&#93;, enforced by a unique
 * index rather than by convention. Deriving it from a magic slug or from "the oldest tenant" would
 * make the organization scope something an operator could rename or delete by accident, and it is
 * the scope the super-admin lives in.
 *
 * Each constant carries the spelling the server uses on the wire, so the Kotlin name can follow
 * Kotlin's conventions without changing what is sent.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * [TenantKind.UNKNOWN] rather than failing the response it arrived in (CONTRACT §27.11 rule 1).
 * Its own wire spelling is the empty string, which no server value is: carrying an unrecognised
 * value back into an update is refused by the server rather than silently written as a spelling it
 * never used. A `when` over these constants needs an `UNKNOWN` branch.
 */
@Serializable(with = TenantKind.Companion.Serializer::class)
enum class TenantKind(val wire: String) {
    STANDARD("standard"),

    ORGANIZATION("organization"),

    /** A value this SDK's copy of the spec does not list; see the type's doc. */
    UNKNOWN("");

    companion object {
        /**
         * Decodes an unrecognised value to [UNKNOWN] instead of throwing.
         *
         * kotlinx.serialization's generated enum serializer raises on a value
         * outside the constants, which fails the WHOLE response — not just the
         * field. That is the failure §27.11 rule 1 exists to prevent.
         */
        internal object Serializer : KSerializer<TenantKind> {
            override val descriptor: SerialDescriptor =
                PrimitiveSerialDescriptor("io.axiam.sdk.management.models.TenantKind", PrimitiveKind.STRING)

            override fun serialize(encoder: Encoder, value: TenantKind) {
                encoder.encodeString(value.wire)
            }

            override fun deserialize(decoder: Decoder): TenantKind {
                val raw = decoder.decodeString()
                return entries.firstOrNull { it != UNKNOWN && it.wire == raw } ?: UNKNOWN
            }
        }
    }
}
