// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * X4 trust for exchanging this provider's tokens (RFC 8693, external issuer). Mirrors
 * &#91;`TokenExchangeTrust`&#93; on the wire rather than reusing it directly so the API surface
 * can carry its own defaults: an admin PUTting a partial block gets the documented default for
 * anything they omitted, instead of a deserialization error listing fields they have never heard
 * of.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property acceptedAudiences Audiences an incoming subject token may name. Required
 *     (non-empty) when `enabled`; there is deliberately no accept-all value.
 * @property enabled Off unless explicitly enabled. Configuring a provider for *login* is not
 *     agreement to accept its tokens as API credentials.
 * @property maxLifetimeSecs Per-provider ceiling on the issued AXIAM token's lifetime.
 * @property maxTokenAgeSecs Bound on `now - iat`, independent of the token's own `exp`.
 * @property scopeMap External asserted value -> AXIAM scopes. Deny-by-default: an external
 *     value with no entry contributes nothing.
 * @property subjectMapping `linked_only` (default) or `jit_provision`.
 */
@Serializable
data class TokenExchangeTrustRequest(
    @SerialName("accepted_audiences") val acceptedAudiences: List<String>? = null,
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("max_lifetime_secs") val maxLifetimeSecs: Long? = null,
    @SerialName("max_token_age_secs") val maxTokenAgeSecs: Long? = null,
    @SerialName("scope_map") val scopeMap: JsonElement? = null,
    @SerialName("subject_mapping") val subjectMapping: String? = null,
)
