// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The UpdateUserRequest schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property email the server's email field
 * @property metadata the server's metadata field
 * @property status the server's status field
 * @property username the server's username field
 */
@Serializable
data class UpdateUserRequest(
    @SerialName("email") val email: String? = null,
    @SerialName("metadata") val metadata: JsonElement? = null,
    @SerialName("status") val status: UserStatus? = null,
    @SerialName("username") val username: String? = null,
)
