// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The UpdateFederationConfigRequest schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property allowedAlgorithms Accepted signature algorithms (CQ-B40/REQ-14 AC-5).
 * @property attributeMap the server's attribute_map field
 * @property clientId the server's client_id field
 * @property clientSecret the server's client_secret field -- SECRET: redacted from toString
 *     and from every rendering except the one request body it is sent in
 * @property enabled the server's enabled field
 * @property idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML assertions
 *     (CQ-B40/REQ-14 AC-5). `Some(None)` clears the stored cert.
 * @property metadataUrl the server's metadata_url field
 * @property provider the server's provider field
 * @property tokenExchange the server's token_exchange field
 */
@Serializable
data class UpdateFederationConfigRequest(
    @SerialName("allowed_algorithms") val allowedAlgorithms: List<String>? = null,
    @SerialName("attribute_map") val attributeMap: JsonElement? = null,
    @SerialName("client_id") val clientId: String? = null,
    @SerialName("client_secret") val clientSecret: @Contextual Sensitive<String>? = null,
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("idp_signing_cert_pem") val idpSigningCertPem: String? = null,
    @SerialName("metadata_url") val metadataUrl: String? = null,
    @SerialName("provider") val provider: String? = null,
    @SerialName("token_exchange") val tokenExchange: TokenExchangeTrustRequest? = null,
)
