// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The UpdateReactorRequest schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property description the server's description field
 * @property enabled the server's enabled field
 * @property events the server's events field
 * @property failurePolicy the server's failure_policy field
 * @property mode the server's mode field
 * @property name the server's name field
 * @property priority the server's priority field
 * @property timeoutMs the server's timeout_ms field
 */
@Serializable
data class UpdateReactorRequest(
    @SerialName("description") val description: String? = null,
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("events") val events: List<String>? = null,
    @SerialName("failure_policy") val failurePolicy: FailurePolicy? = null,
    @SerialName("mode") val mode: ReactorMode? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("priority") val priority: Int? = null,
    @SerialName("timeout_ms") val timeoutMs: Int? = null,
)
