// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.Sensitive
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The UpdateWebhookRequest schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property enabled the server's enabled field
 * @property events the server's events field
 * @property retryPolicy the server's retry_policy field
 * @property secret New HMAC-SHA256 shared secret (D-02 secret rotation). Encrypted server-side
 *     with AES-256-GCM before storage; omit to leave the existing secret untouched. -- SECRET:
 *     redacted from toString and from every rendering except the one request body it is sent in
 * @property url the server's url field
 */
@Serializable
data class UpdateWebhookRequest(
    @SerialName("enabled") val enabled: Boolean? = null,
    @SerialName("events") val events: List<String>? = null,
    @SerialName("retry_policy") val retryPolicy: RetryPolicy? = null,
    @SerialName("secret") val secret: @Contextual Sensitive<String>? = null,
    @SerialName("url") val url: String? = null,
)
