// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.UuidSerializer
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * The UpdateResourceRequest schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Naming
 * the properties you mean to change is the whole API — there is no builder because Kotlin does not
 * need one, and no way to accidentally send a field you did not name.
 *
 * @property metadata the server's metadata field
 * @property name the server's name field
 * @property parentId the server's parent_id field
 * @property resourceType the server's resource_type field
 */
@Serializable
data class UpdateResourceRequest(
    @SerialName("metadata") val metadata: JsonElement? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("parent_id") val parentId: @Serializable(with = UuidSerializer::class) UUID? = null,
    @SerialName("resource_type") val resourceType: String? = null,
)
