// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Public-safe user representation (no password_hash, no mfa_secret).
 *
 * @property createdAt the server's created_at field
 * @property email the server's email field
 * @property emailVerified True when the user's email address has been verified
 *     (`email_verified_at` is set). Exposed for the admin UI / profile.
 * @property failedLoginAttempts Number of consecutive failed login attempts.
 * @property id the server's id field
 * @property isLocked Whether the account is currently locked (locked_until is in the future).
 * @property lockedUntil Timestamp until which the account is locked, if any.
 * @property metadata the server's metadata field
 * @property mfaEnabled the server's mfa_enabled field
 * @property status the server's status field
 * @property tenantId the server's tenant_id field
 * @property updatedAt the server's updated_at field
 * @property username the server's username field
 */
@Serializable
data class UserResponse(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("email") val email: String,
    @SerialName("email_verified") val emailVerified: Boolean,
    @SerialName("failed_login_attempts") val failedLoginAttempts: Int,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("is_locked") val isLocked: Boolean,
    @SerialName("locked_until") val lockedUntil: @Serializable(with = InstantSerializer::class) Instant? = null,
    @SerialName("metadata") val metadata: JsonElement,
    @SerialName("mfa_enabled") val mfaEnabled: Boolean,
    @SerialName("status") val status: UserStatus,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("username") val username: String,
)
