// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * WebAuthn ceremony policy. One field today. It is a struct rather than a bare field on
 * &#91;`SecuritySettings`&#93; so that the next WebAuthn control has an obvious home, and so the
 * admin UI can group them. The *attestation* policy is deliberately not here: it lives in
 * &#91;`crate::models::webauthn_policy::WebauthnAttestationPolicy`&#93;, is tenant-only, and
 * cannot join this model because AAGUID allow/block lists have no "more restrictive than" ordering
 * to validate an override against. User verification does, so it can.
 *
 * @property webauthnUserVerification How hard the authenticator must prove *who* is present.
 *     Applies to enrolment and to second-factor authentication. Usernameless sign-in is held to
 *     `required` whatever this says — see &#91;`WebauthnUserVerification`&#93;.
 */
@Serializable
data class WebauthnPolicy(
    @SerialName("webauthn_user_verification") val webauthnUserVerification: String,
)
