// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models

import io.axiam.sdk.management.InstantSerializer
import io.axiam.sdk.management.UuidSerializer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Webhook response — omits the shared secret.
 *
 * @property createdAt the server's created_at field
 * @property enabled the server's enabled field
 * @property events the server's events field
 * @property id the server's id field
 * @property retryPolicy the server's retry_policy field
 * @property tenantId the server's tenant_id field
 * @property updatedAt the server's updated_at field
 * @property url the server's url field
 */
@Serializable
data class WebhookResponse(
    @SerialName("created_at") val createdAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("events") val events: List<String>,
    @SerialName("id") val id: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("retry_policy") val retryPolicy: RetryPolicy,
    @SerialName("tenant_id") val tenantId: @Serializable(with = UuidSerializer::class) UUID,
    @SerialName("updated_at") val updatedAt: @Serializable(with = InstantSerializer::class) Instant,
    @SerialName("url") val url: String,
)
