package io.axiam.sdk.oidc

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.util.Base64

class OidcPkceTest {

    @Test
    fun `RFC 7636 Appendix B test vector`() {
        val challenge = OidcPkce.computeCodeChallenge(OidcTestKit.RFC7636_VERIFIER)
        assertEquals(OidcTestKit.RFC7636_CHALLENGE, challenge)
    }

    @Test
    fun `code_challenge_method is S256 only`() {
        assertEquals("S256", OidcPkce.CODE_CHALLENGE_METHOD_S256)
        assertNotEquals("plain", OidcPkce.CODE_CHALLENGE_METHOD_S256)
    }

    @Test
    fun `randomUrlSafeToken has at least 128 bits of entropy and is base64url without padding`() {
        val token = OidcPkce.randomUrlSafeToken()
        assertTrue(token.isNotBlank())
        assertTrue(!token.contains('='), "must be unpadded")
        assertTrue(!token.contains('+') && !token.contains('/'), "must be URL-safe alphabet")
        // 32 raw bytes (256 bits, well above the 128-bit floor) base64url-encode to 43 chars unpadded.
        assertEquals(43, token.length)
        Base64.getUrlDecoder().decode(token) // does not throw
    }

    @Test
    fun `randomUrlSafeToken values are unique across calls`() {
        val tokens = (1..200).map { OidcPkce.randomUrlSafeToken() }.toSet()
        assertEquals(200, tokens.size)
    }

    @Test
    fun `state and nonce generated by separate calls are never equal`() {
        repeat(50) {
            assertNotEquals(OidcPkce.randomUrlSafeToken(), OidcPkce.randomUrlSafeToken())
        }
    }

    @Test
    fun `generateCodeVerifier produces a 43-character verifier from the unreserved set, wrapped Sensitive`() {
        val verifier = OidcPkce.generateCodeVerifier()
        assertEquals("[SENSITIVE]", verifier.toString())
        val raw = verifier.expose()
        assertEquals(43, raw.length)
        assertTrue(raw.all { it.isLetterOrDigit() || it == '-' || it == '.' || it == '_' || it == '~' })
    }

    @Test
    fun `custom byte length is honored by randomUrlSafeToken`() {
        val token = OidcPkce.randomUrlSafeToken(16)
        // 16 raw bytes base64url-encode to 22 unpadded chars (ceil(16*8/6)).
        assertEquals(22, token.length)
    }
}
